-- Raw NBA game-log tables — one table per nba_api endpoint.
--   raw.nba_player_base      ← PlayerGameLogs(measure_type='Base')
--   raw.nba_player_adv       ← PlayerGameLogs(measure_type='Advanced')
--   raw.nba_team_base        ← TeamGameLogs(measure_type='Base')
--   raw.nba_team_adv         ← TeamGameLogs(measure_type='Advanced')
--   raw.nba_player_tracking  ← BoxScorePlayerTrackV3 (per-game tracking / position)
--
-- Column names are the endpoint fields after snake_case normalization
-- (GAME_ID → game_id, firstName → first_name). Only game_id / player_id /
-- team_id are renamed in fetch.py; everything else is the API as returned.
-- fetched_at is stamped on every upsert.

CREATE SCHEMA IF NOT EXISTS raw;

-- ── raw.nba_player_base ───────────────────────────────────────────────────────
-- Source: PlayerGameLogs(measure_type='Base')

CREATE TABLE IF NOT EXISTS raw.nba_player_base (
    game_id               TEXT        NOT NULL,
    player_id             BIGINT      NOT NULL,
    fetched_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    season_year           TEXT,
    player_name           TEXT,
    nickname              TEXT,
    team_id               BIGINT,
    team_abbreviation     TEXT,
    team_name             TEXT,
    game_date             TEXT,
    matchup               TEXT,
    wl                    TEXT,
    min                   NUMERIC,
    fgm                   NUMERIC,
    fga                   NUMERIC,
    fg_pct                NUMERIC,
    fg3m                  NUMERIC,
    fg3a                  NUMERIC,
    fg3_pct               NUMERIC,
    ftm                   NUMERIC,
    fta                   NUMERIC,
    ft_pct                NUMERIC,
    oreb                  NUMERIC,
    dreb                  NUMERIC,
    reb                   NUMERIC,
    ast                   NUMERIC,
    tov                   NUMERIC,
    stl                   NUMERIC,
    blk                   NUMERIC,
    blka                  NUMERIC,
    pf                    NUMERIC,
    pfd                   NUMERIC,
    pts                   NUMERIC,
    plus_minus            NUMERIC,
    nba_fantasy_pts       NUMERIC,
    dd2                   NUMERIC,
    td3                   NUMERIC,
    wnba_fantasy_pts      NUMERIC,
    gp_rank               NUMERIC,
    w_rank                NUMERIC,
    l_rank                NUMERIC,
    w_pct_rank            NUMERIC,
    min_rank              NUMERIC,
    fgm_rank              NUMERIC,
    fga_rank              NUMERIC,
    fg_pct_rank           NUMERIC,
    fg3m_rank             NUMERIC,
    fg3a_rank             NUMERIC,
    fg3_pct_rank          NUMERIC,
    ftm_rank              NUMERIC,
    fta_rank              NUMERIC,
    ft_pct_rank           NUMERIC,
    oreb_rank             NUMERIC,
    dreb_rank             NUMERIC,
    reb_rank              NUMERIC,
    ast_rank              NUMERIC,
    tov_rank              NUMERIC,
    stl_rank              NUMERIC,
    blk_rank              NUMERIC,
    blka_rank             NUMERIC,
    pf_rank               NUMERIC,
    pfd_rank              NUMERIC,
    pts_rank              NUMERIC,
    plus_minus_rank       NUMERIC,
    nba_fantasy_pts_rank  NUMERIC,
    dd2_rank              NUMERIC,
    td3_rank              NUMERIC,
    wnba_fantasy_pts_rank NUMERIC,
    available_flag        TEXT,
    min_sec               TEXT,
    team_count            NUMERIC,

    PRIMARY KEY (game_id, player_id)
);

-- ── raw.nba_player_adv ────────────────────────────────────────────────────────
-- Source: PlayerGameLogs(measure_type='Advanced')

CREATE TABLE IF NOT EXISTS raw.nba_player_adv (
    game_id               TEXT        NOT NULL,
    player_id             BIGINT      NOT NULL,
    fetched_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    season_year           TEXT,
    player_name           TEXT,
    nickname              TEXT,
    team_id               BIGINT,
    team_abbreviation     TEXT,
    team_name             TEXT,
    game_date             TEXT,
    matchup               TEXT,
    wl                    TEXT,
    min                   NUMERIC,
    e_off_rating          NUMERIC,
    off_rating            NUMERIC,
    sp_work_off_rating    NUMERIC,
    e_def_rating          NUMERIC,
    def_rating            NUMERIC,
    sp_work_def_rating    NUMERIC,
    e_net_rating          NUMERIC,
    net_rating            NUMERIC,
    sp_work_net_rating    NUMERIC,
    ast_pct               NUMERIC,
    ast_to                NUMERIC,
    ast_ratio             NUMERIC,
    oreb_pct              NUMERIC,
    dreb_pct              NUMERIC,
    reb_pct               NUMERIC,
    tm_tov_pct            NUMERIC,
    e_tov_pct             NUMERIC,
    efg_pct               NUMERIC,
    ts_pct                NUMERIC,
    usg_pct               NUMERIC,
    e_usg_pct             NUMERIC,
    e_pace                NUMERIC,
    pace                  NUMERIC,
    pace_per40            NUMERIC,
    sp_work_pace          NUMERIC,
    pie                   NUMERIC,
    poss                  NUMERIC,
    fgm                   NUMERIC,
    fga                   NUMERIC,
    fgm_pg                NUMERIC,
    fga_pg                NUMERIC,
    fg_pct                NUMERIC,
    gp_rank               NUMERIC,
    w_rank                NUMERIC,
    l_rank                NUMERIC,
    w_pct_rank            NUMERIC,
    min_rank              NUMERIC,
    e_off_rating_rank     NUMERIC,
    off_rating_rank       NUMERIC,
    sp_work_off_rating_rank NUMERIC,
    e_def_rating_rank     NUMERIC,
    def_rating_rank       NUMERIC,
    sp_work_def_rating_rank NUMERIC,
    e_net_rating_rank     NUMERIC,
    net_rating_rank       NUMERIC,
    sp_work_net_rating_rank NUMERIC,
    ast_pct_rank          NUMERIC,
    ast_to_rank           NUMERIC,
    ast_ratio_rank        NUMERIC,
    oreb_pct_rank         NUMERIC,
    dreb_pct_rank         NUMERIC,
    reb_pct_rank          NUMERIC,
    tm_tov_pct_rank       NUMERIC,
    e_tov_pct_rank        NUMERIC,
    efg_pct_rank          NUMERIC,
    ts_pct_rank           NUMERIC,
    usg_pct_rank          NUMERIC,
    e_usg_pct_rank        NUMERIC,
    e_pace_rank           NUMERIC,
    pace_rank             NUMERIC,
    sp_work_pace_rank     NUMERIC,
    pie_rank              NUMERIC,
    fgm_rank              NUMERIC,
    fga_rank              NUMERIC,
    fgm_pg_rank           NUMERIC,
    fga_pg_rank           NUMERIC,
    fg_pct_rank           NUMERIC,
    available_flag        TEXT,
    min_sec               TEXT,
    team_count            NUMERIC,

    PRIMARY KEY (game_id, player_id)
);

-- ── raw.nba_team_base ─────────────────────────────────────────────────────────
-- Source: TeamGameLogs(measure_type='Base')

CREATE TABLE IF NOT EXISTS raw.nba_team_base (
    game_id               TEXT        NOT NULL,
    team_id               BIGINT      NOT NULL,
    fetched_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    season_year           TEXT,
    team_abbreviation     TEXT,
    team_name             TEXT,
    game_date             TEXT,
    matchup               TEXT,
    wl                    TEXT,
    min                   NUMERIC,
    fgm                   NUMERIC,
    fga                   NUMERIC,
    fg_pct                NUMERIC,
    fg3m                  NUMERIC,
    fg3a                  NUMERIC,
    fg3_pct               NUMERIC,
    ftm                   NUMERIC,
    fta                   NUMERIC,
    ft_pct                NUMERIC,
    oreb                  NUMERIC,
    dreb                  NUMERIC,
    reb                   NUMERIC,
    ast                   NUMERIC,
    tov                   NUMERIC,
    stl                   NUMERIC,
    blk                   NUMERIC,
    blka                  NUMERIC,
    pf                    NUMERIC,
    pfd                   NUMERIC,
    pts                   NUMERIC,
    plus_minus            NUMERIC,
    gp_rank               NUMERIC,
    w_rank                NUMERIC,
    l_rank                NUMERIC,
    w_pct_rank            NUMERIC,
    min_rank              NUMERIC,
    fgm_rank              NUMERIC,
    fga_rank              NUMERIC,
    fg_pct_rank           NUMERIC,
    fg3m_rank             NUMERIC,
    fg3a_rank             NUMERIC,
    fg3_pct_rank          NUMERIC,
    ftm_rank              NUMERIC,
    fta_rank              NUMERIC,
    ft_pct_rank           NUMERIC,
    oreb_rank             NUMERIC,
    dreb_rank             NUMERIC,
    reb_rank              NUMERIC,
    ast_rank              NUMERIC,
    tov_rank              NUMERIC,
    stl_rank              NUMERIC,
    blk_rank              NUMERIC,
    blka_rank             NUMERIC,
    pf_rank               NUMERIC,
    pfd_rank              NUMERIC,
    pts_rank              NUMERIC,
    plus_minus_rank       NUMERIC,
    available_flag        TEXT,

    PRIMARY KEY (game_id, team_id)
);

-- ── raw.nba_team_adv ──────────────────────────────────────────────────────────
-- Source: TeamGameLogs(measure_type='Advanced')

CREATE TABLE IF NOT EXISTS raw.nba_team_adv (
    game_id               TEXT        NOT NULL,
    team_id               BIGINT      NOT NULL,
    fetched_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    season_year           TEXT,
    team_abbreviation     TEXT,
    team_name             TEXT,
    game_date             TEXT,
    matchup               TEXT,
    wl                    TEXT,
    min                   NUMERIC,
    e_off_rating          NUMERIC,
    off_rating            NUMERIC,
    e_def_rating          NUMERIC,
    def_rating            NUMERIC,
    e_net_rating          NUMERIC,
    net_rating            NUMERIC,
    ast_pct               NUMERIC,
    ast_to                NUMERIC,
    ast_ratio             NUMERIC,
    oreb_pct              NUMERIC,
    dreb_pct              NUMERIC,
    reb_pct               NUMERIC,
    tm_tov_pct            NUMERIC,
    efg_pct               NUMERIC,
    ts_pct                NUMERIC,
    e_pace                NUMERIC,
    pace                  NUMERIC,
    pace_per40            NUMERIC,
    poss                  NUMERIC,
    pie                   NUMERIC,
    gp_rank               NUMERIC,
    w_rank                NUMERIC,
    l_rank                NUMERIC,
    w_pct_rank            NUMERIC,
    min_rank              NUMERIC,
    off_rating_rank       NUMERIC,
    def_rating_rank       NUMERIC,
    net_rating_rank       NUMERIC,
    ast_pct_rank          NUMERIC,
    ast_to_rank           NUMERIC,
    ast_ratio_rank        NUMERIC,
    oreb_pct_rank         NUMERIC,
    dreb_pct_rank         NUMERIC,
    reb_pct_rank          NUMERIC,
    tm_tov_pct_rank       NUMERIC,
    efg_pct_rank          NUMERIC,
    ts_pct_rank           NUMERIC,
    pace_rank             NUMERIC,
    pie_rank              NUMERIC,
    available_flag        TEXT,

    PRIMARY KEY (game_id, team_id)
);

-- ── raw.nba_player_tracking ───────────────────────────────────────────────────
-- Source: BoxScorePlayerTrackV3 — one row per player per game.
-- position is '' for bench players, G/F/C for starters.

CREATE TABLE IF NOT EXISTS raw.nba_player_tracking (
    game_id                               TEXT        NOT NULL,
    player_id                             BIGINT      NOT NULL,
    fetched_at                            TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    team_id                               BIGINT,
    team_city                             TEXT,
    team_name                             TEXT,
    team_tricode                          TEXT,
    team_slug                             TEXT,
    first_name                            TEXT,
    family_name                           TEXT,
    name_i                                TEXT,
    player_slug                           TEXT,
    position                              TEXT,
    comment                               TEXT,
    jersey_num                            TEXT,
    minutes                               TEXT,
    speed                                 NUMERIC,
    distance                              NUMERIC,
    rebound_chances_offensive             NUMERIC,
    rebound_chances_defensive             NUMERIC,
    rebound_chances_total                 NUMERIC,
    touches                               NUMERIC,
    secondary_assists                     NUMERIC,
    free_throw_assists                    NUMERIC,
    passes                                NUMERIC,
    assists                               NUMERIC,
    contested_field_goals_made            NUMERIC,
    contested_field_goals_attempted       NUMERIC,
    contested_field_goal_percentage       NUMERIC,
    uncontested_field_goals_made          NUMERIC,
    uncontested_field_goals_attempted     NUMERIC,
    uncontested_field_goals_percentage    NUMERIC,
    field_goal_percentage                 NUMERIC,
    defended_at_rim_field_goals_made      NUMERIC,
    defended_at_rim_field_goals_attempted NUMERIC,
    defended_at_rim_field_goal_percentage NUMERIC,

    PRIMARY KEY (game_id, player_id)
);
