-- Gold layer: NBA APM model training / inference frame.
-- Source: src.pipeline.gold.build_apm_gold_from_silver(..., league="nba")
-- Upload: src.utils.db.upsert_prop_gold("apm", df, league="nba")
-- Feature columns match src.pipeline.features.apm_features.APM_FEATURES.

CREATE SCHEMA IF NOT EXISTS gold;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'gold' AND table_name = 'player_apm_model'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'gold' AND table_name = 'nba_player_apm_model'
    ) THEN
        ALTER TABLE gold.player_apm_model RENAME TO nba_player_apm_model;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS gold.nba_player_apm_model (
    game_id                                 TEXT        NOT NULL,
    player_id                               BIGINT      NOT NULL,
    built_at                                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    season                                  TEXT,
    player_name                             TEXT,
    game_date                               DATE,
    ast_per_min                             NUMERIC,
    min                                     NUMERIC,
    starting                                SMALLINT,
    age                                     NUMERIC,
    position_encoded                        SMALLINT,
    is_home                                 SMALLINT,
    is_playoff                              SMALLINT,
    days_rest                               NUMERIC,
    is_back_to_back                         SMALLINT,
    games_played_this_season                SMALLINT,
    games_played_career                     SMALLINT,
    starting_rate_last10                    NUMERIC,
    min_trend_5v20                          NUMERIC,
    player_ast_roll5_mean                   NUMERIC,
    player_ast_roll5_std                    NUMERIC,
    player_ast_roll10_mean                  NUMERIC,
    player_ast_roll10_std                   NUMERIC,
    player_ast_roll20_mean                  NUMERIC,
    player_ast_roll20_std                   NUMERIC,
    player_ast_ewma                         NUMERIC,
    player_ast_expanding_mean               NUMERIC,
    player_ast_per_min_roll5_mean           NUMERIC,
    player_ast_per_min_roll5_std            NUMERIC,
    player_ast_per_min_roll10_mean          NUMERIC,
    player_ast_per_min_roll10_std           NUMERIC,
    player_ast_per_min_roll20_mean          NUMERIC,
    player_ast_per_min_roll20_std           NUMERIC,
    player_ast_per_min_ewma                 NUMERIC,
    player_ast_per_min_expanding_mean       NUMERIC,
    player_ast_pct_roll5_mean               NUMERIC,
    player_ast_pct_roll5_std                NUMERIC,
    player_ast_pct_roll10_mean              NUMERIC,
    player_ast_pct_roll10_std               NUMERIC,
    player_ast_pct_roll20_mean              NUMERIC,
    player_ast_pct_roll20_std               NUMERIC,
    player_ast_pct_ewma                     NUMERIC,
    player_ast_pct_expanding_mean           NUMERIC,
    player_ast_to_roll5_mean                NUMERIC,
    player_ast_to_roll5_std                 NUMERIC,
    player_ast_to_roll10_mean               NUMERIC,
    player_ast_to_roll10_std                NUMERIC,
    player_ast_to_roll20_mean               NUMERIC,
    player_ast_to_roll20_std                NUMERIC,
    player_ast_to_ewma                      NUMERIC,
    player_ast_to_expanding_mean            NUMERIC,
    player_ast_ratio_roll5_mean             NUMERIC,
    player_ast_ratio_roll5_std              NUMERIC,
    player_ast_ratio_roll10_mean            NUMERIC,
    player_ast_ratio_roll10_std             NUMERIC,
    player_ast_ratio_roll20_mean            NUMERIC,
    player_ast_ratio_roll20_std             NUMERIC,
    player_ast_ratio_ewma                   NUMERIC,
    player_ast_ratio_expanding_mean         NUMERIC,
    player_min_roll5_mean                   NUMERIC,
    player_min_roll5_std                    NUMERIC,
    player_min_roll10_mean                  NUMERIC,
    player_min_roll10_std                   NUMERIC,
    player_min_roll20_mean                  NUMERIC,
    player_min_roll20_std                   NUMERIC,
    player_min_ewma                         NUMERIC,
    player_min_expanding_mean               NUMERIC,
    player_poss_roll5_mean                  NUMERIC,
    player_poss_roll5_std                   NUMERIC,
    player_poss_roll10_mean                 NUMERIC,
    player_poss_roll10_std                  NUMERIC,
    player_poss_roll20_mean                 NUMERIC,
    player_poss_roll20_std                  NUMERIC,
    player_poss_ewma                        NUMERIC,
    player_poss_expanding_mean              NUMERIC,
    player_tchs_roll5_mean                  NUMERIC,
    player_tchs_roll5_std                   NUMERIC,
    player_tchs_roll10_mean                 NUMERIC,
    player_tchs_roll10_std                  NUMERIC,
    player_tchs_roll20_mean                 NUMERIC,
    player_tchs_roll20_std                  NUMERIC,
    player_tchs_ewma                        NUMERIC,
    player_tchs_expanding_mean              NUMERIC,
    player_pass_roll5_mean                  NUMERIC,
    player_pass_roll5_std                   NUMERIC,
    player_pass_roll10_mean                 NUMERIC,
    player_pass_roll10_std                  NUMERIC,
    player_pass_roll20_mean                 NUMERIC,
    player_pass_roll20_std                  NUMERIC,
    player_pass_ewma                        NUMERIC,
    player_pass_expanding_mean              NUMERIC,
    player_sast_roll5_mean                  NUMERIC,
    player_sast_roll5_std                   NUMERIC,
    player_sast_roll10_mean                 NUMERIC,
    player_sast_roll10_std                  NUMERIC,
    player_sast_roll20_mean                 NUMERIC,
    player_sast_roll20_std                  NUMERIC,
    player_sast_ewma                        NUMERIC,
    player_sast_expanding_mean              NUMERIC,
    player_ftast_roll5_mean                 NUMERIC,
    player_ftast_roll5_std                  NUMERIC,
    player_ftast_roll10_mean                NUMERIC,
    player_ftast_roll10_std                 NUMERIC,
    player_ftast_roll20_mean                NUMERIC,
    player_ftast_roll20_std                 NUMERIC,
    player_ftast_ewma                       NUMERIC,
    player_ftast_expanding_mean             NUMERIC,
    player_usg_pct_roll5_mean               NUMERIC,
    player_usg_pct_roll5_std                NUMERIC,
    player_usg_pct_roll10_mean              NUMERIC,
    player_usg_pct_roll10_std               NUMERIC,
    player_usg_pct_roll20_mean              NUMERIC,
    player_usg_pct_roll20_std               NUMERIC,
    player_usg_pct_ewma                     NUMERIC,
    player_usg_pct_expanding_mean           NUMERIC,
    player_pts_per_min_roll5_mean           NUMERIC,
    player_pts_per_min_roll5_std            NUMERIC,
    player_pts_per_min_roll10_mean          NUMERIC,
    player_pts_per_min_roll10_std           NUMERIC,
    player_pts_per_min_roll20_mean          NUMERIC,
    player_pts_per_min_roll20_std           NUMERIC,
    player_pts_per_min_ewma                 NUMERIC,
    player_pts_per_min_expanding_mean       NUMERIC,
    player_reb_per_min_roll5_mean           NUMERIC,
    player_reb_per_min_roll5_std            NUMERIC,
    player_reb_per_min_roll10_mean          NUMERIC,
    player_reb_per_min_roll10_std           NUMERIC,
    player_reb_per_min_roll20_mean          NUMERIC,
    player_reb_per_min_roll20_std           NUMERIC,
    player_reb_per_min_ewma                 NUMERIC,
    player_reb_per_min_expanding_mean       NUMERIC,
    player_tov_roll5_mean                   NUMERIC,
    player_tov_roll5_std                    NUMERIC,
    player_tov_roll10_mean                  NUMERIC,
    player_tov_roll10_std                   NUMERIC,
    player_tov_roll20_mean                  NUMERIC,
    player_tov_roll20_std                   NUMERIC,
    player_tov_ewma                         NUMERIC,
    player_tov_expanding_mean               NUMERIC,
    player_pie_roll5_mean                   NUMERIC,
    player_pie_roll5_std                    NUMERIC,
    player_pie_roll10_mean                  NUMERIC,
    player_pie_roll10_std                   NUMERIC,
    player_pie_roll20_mean                  NUMERIC,
    player_pie_roll20_std                   NUMERIC,
    player_pie_ewma                         NUMERIC,
    player_pie_expanding_mean               NUMERIC,
    player_ast_season_mean                  NUMERIC,
    player_ast_per_min_season_mean          NUMERIC,
    player_ast_pct_season_mean              NUMERIC,
    player_ast_to_season_mean               NUMERIC,
    player_ast_ratio_season_mean            NUMERIC,
    player_min_season_mean                  NUMERIC,
    player_poss_season_mean                 NUMERIC,
    player_tchs_season_mean                 NUMERIC,
    player_pass_season_mean                 NUMERIC,
    player_sast_season_mean                 NUMERIC,
    player_ftast_season_mean                NUMERIC,
    player_usg_pct_season_mean              NUMERIC,
    player_pts_per_min_season_mean          NUMERIC,
    player_reb_per_min_season_mean          NUMERIC,
    player_tov_season_mean                  NUMERIC,
    player_pie_season_mean                  NUMERIC,
    own_team_team_ast_roll5_mean            NUMERIC,
    own_team_team_ast_roll5_std             NUMERIC,
    own_team_team_ast_roll10_mean           NUMERIC,
    own_team_team_ast_roll10_std            NUMERIC,
    own_team_team_ast_ewma                  NUMERIC,
    own_team_team_ast_expanding_mean        NUMERIC,
    own_team_team_ast_pct_roll5_mean        NUMERIC,
    own_team_team_ast_pct_roll5_std         NUMERIC,
    own_team_team_ast_pct_roll10_mean       NUMERIC,
    own_team_team_ast_pct_roll10_std        NUMERIC,
    own_team_team_ast_pct_ewma              NUMERIC,
    own_team_team_ast_pct_expanding_mean    NUMERIC,
    own_team_team_ast_ratio_roll5_mean      NUMERIC,
    own_team_team_ast_ratio_roll5_std       NUMERIC,
    own_team_team_ast_ratio_roll10_mean     NUMERIC,
    own_team_team_ast_ratio_roll10_std      NUMERIC,
    own_team_team_ast_ratio_ewma            NUMERIC,
    own_team_team_ast_ratio_expanding_mean  NUMERIC,
    own_team_team_ast_to_roll5_mean         NUMERIC,
    own_team_team_ast_to_roll5_std          NUMERIC,
    own_team_team_ast_to_roll10_mean        NUMERIC,
    own_team_team_ast_to_roll10_std         NUMERIC,
    own_team_team_ast_to_ewma               NUMERIC,
    own_team_team_ast_to_expanding_mean     NUMERIC,
    own_team_team_pace_roll5_mean           NUMERIC,
    own_team_team_pace_roll5_std            NUMERIC,
    own_team_team_pace_roll10_mean          NUMERIC,
    own_team_team_pace_roll10_std           NUMERIC,
    own_team_team_pace_ewma                 NUMERIC,
    own_team_team_pace_expanding_mean       NUMERIC,
    own_team_team_off_rating_roll5_mean     NUMERIC,
    own_team_team_off_rating_roll5_std      NUMERIC,
    own_team_team_off_rating_roll10_mean    NUMERIC,
    own_team_team_off_rating_roll10_std     NUMERIC,
    own_team_team_off_rating_ewma           NUMERIC,
    own_team_team_off_rating_expanding_mean NUMERIC,
    own_team_team_poss_roll5_mean           NUMERIC,
    own_team_team_poss_roll5_std            NUMERIC,
    own_team_team_poss_roll10_mean          NUMERIC,
    own_team_team_poss_roll10_std           NUMERIC,
    own_team_team_poss_ewma                 NUMERIC,
    own_team_team_poss_expanding_mean       NUMERIC,
    opp_team_team_pace_roll5_mean           NUMERIC,
    opp_team_team_pace_roll5_std            NUMERIC,
    opp_team_team_pace_roll10_mean          NUMERIC,
    opp_team_team_pace_roll10_std           NUMERIC,
    opp_team_team_pace_ewma                 NUMERIC,
    opp_team_team_pace_expanding_mean       NUMERIC,
    opp_team_team_def_rating_roll5_mean     NUMERIC,
    opp_team_team_def_rating_roll5_std      NUMERIC,
    opp_team_team_def_rating_roll10_mean    NUMERIC,
    opp_team_team_def_rating_roll10_std     NUMERIC,
    opp_team_team_def_rating_ewma           NUMERIC,
    opp_team_team_def_rating_expanding_mean NUMERIC,
    opp_team_team_tov_roll5_mean            NUMERIC,
    opp_team_team_tov_roll5_std             NUMERIC,
    opp_team_team_tov_roll10_mean           NUMERIC,
    opp_team_team_tov_roll10_std            NUMERIC,
    opp_team_team_tov_ewma                  NUMERIC,
    opp_team_team_tov_expanding_mean        NUMERIC,
    opp_team_team_tm_tov_pct_roll5_mean     NUMERIC,
    opp_team_team_tm_tov_pct_roll5_std      NUMERIC,
    opp_team_team_tm_tov_pct_roll10_mean    NUMERIC,
    opp_team_team_tm_tov_pct_roll10_std     NUMERIC,
    opp_team_team_tm_tov_pct_ewma           NUMERIC,
    opp_team_team_tm_tov_pct_expanding_mean NUMERIC,
    opp_team_team_reb_pct_roll5_mean        NUMERIC,
    opp_team_team_reb_pct_roll5_std         NUMERIC,
    opp_team_team_reb_pct_roll10_mean       NUMERIC,
    opp_team_team_reb_pct_roll10_std        NUMERIC,
    opp_team_team_reb_pct_ewma              NUMERIC,
    opp_team_team_reb_pct_expanding_mean    NUMERIC,

    PRIMARY KEY (game_id, player_id)
);

CREATE INDEX IF NOT EXISTS idx_gold_nba_apm_season ON gold.nba_player_apm_model (season);
CREATE INDEX IF NOT EXISTS idx_gold_nba_apm_date ON gold.nba_player_apm_model (game_date);
CREATE INDEX IF NOT EXISTS idx_gold_nba_apm_player ON gold.nba_player_apm_model (player_id);
