version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 15432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - /Users/viet/Documents/projects.nosyc/prizepicks
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - /Users/viet/Documents/projects.nosyc/prizepicks

networks: 
  postgres-network:
    driver: bridge
