import type { GameDetail } from "./types";

export const detail: GameDetail = {
  espnEventId: "401749001",
  league: "wnba",
  status: "live",
  statusLabel: "4:13 - 1st",
  venue: "Mortgage Matchup Center",
  away: {
    id: "away1",
    abbrev: "GS",
    name: "Golden State Valkyries",
    score: 10,
    color: "#5B2C6F",
  },
  home: {
    id: "home1",
    abbrev: "PHX",
    name: "Phoenix Mercury",
    score: 9,
    color: "#E56020",
  },
  fgMade: 1,
  fgAttempted: 2,
  latestPlay: {
    id: "p1",
    clock: "4:29",
    period: 1,
    text: "Laeticia Amihere makes two point shot",
    teamId: "away1",
  },
  shots: [
    {
      id: "s1",
      teamId: "away1",
      playerName: "A. Player",
      made: true,
      x: 25,
      y: 5,
      period: 1,
      clock: "8:00",
    },
    {
      id: "s2",
      teamId: "home1",
      playerName: "B. Player",
      made: false,
      x: 20,
      y: 10,
      period: 1,
      clock: "7:00",
    },
  ],
  plays: [
    {
      id: "pl1",
      teamId: "away1",
      period: 1,
      clock: "10:00",
      text: "Tip off won by Golden State",
      scoring: false,
      awayScore: 0,
      homeScore: 0,
      shooting: false,
    },
    {
      id: "pl2",
      teamId: "away1",
      period: 1,
      clock: "8:00",
      text: "A. Player makes two point shot",
      scoring: true,
      awayScore: 2,
      homeScore: 0,
      shooting: true,
    },
    {
      id: "pl3",
      teamId: "home1",
      period: 2,
      clock: "9:00",
      text: "B. Player makes three point shot",
      scoring: true,
      awayScore: 2,
      homeScore: 3,
      shooting: true,
    },
  ],
};
