 -- 001_raw_gamelogs.sql
-- Creates the five raw game-log tables that mirror exactly what the NBA API returns.
-- Run once: Supabase Dashboard → SQL Editor → paste and run.
--
-- Each table is the "bronze" source-of-truth for one NBAGameLogs DataFrame:
--   raw.player_base     ← PlayerGameLogs(measure_type='Base')
--   raw.player_adv      ← PlayerGameLogs(measure_type='Advanced')
--   raw.team_base       ← TeamGameLogs(measure_type='Base')
--   raw.team_adv        ← TeamGameLogs(measure_type='Advanced')
--   raw.start_positions ← BoxScorePlayerTrackV3 (per-game tracking / START_POSITION)
--
-- Primary keys are the natural composite keys used by NBAGameLogs.build() for its merges.
-- fetched_at records when Python last wrote this row (updated on every upsert).
-- All stat columns are NUMERIC so downstream casts are lossless.

CREATE SCHEMA IF NOT EXISTS raw;

-- ── raw.player_base ───────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS raw.player_base (
    -- identity / join keys
    game_id               TEXT        NOT NULL,
    player_id             BIGINT      NOT NULL,
    -- lineage
    fetched_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- descriptive
    season_year           TEXT,
    player_name           TEXT,
    nickname              TEXT,
    team_id               BIGINT,
    team_abbreviation     TEXT,
    team_name             TEXT,
    game_date             TEXT,
    matchup               TEXT,
    wl                    TEXT,
    available_flag        TEXT,
    -- box-score stats
    min                   NUMERIC,
    fgm                   NUMERIC,
    fga                   NUMERIC,
    fg_pct                NUMERIC,
    fg3m                  NUMERIC,
    fg3a                  NUMERIC,
    fg3_pct               NUMERIC,
    ftm                   NUMERIC,
    fta                   NUMERIC,
    ft_pct                NUMERIC,
    oreb                  NUMERIC,
    dreb                  NUMERIC,
    reb                   NUMERIC,
    ast                   NUMERIC,
    tov                   NUMERIC,
    stl                   NUMERIC,
    blk                   NUMERIC,
    blka                  NUMERIC,
    pf                    NUMERIC,
    pfd                   NUMERIC,
    pts                   NUMERIC,
    plus_minus            NUMERIC,
    nba_fantasy_pts       NUMERIC,
    dd2                   NUMERIC,
    td3                   NUMERIC,
    wnba_fantasy_pts      NUMERIC,
    -- league rank columns (dropped in silver layer via _clean(), kept here for completeness)
    gp_rank               NUMERIC,
    w_rank                NUMERIC,
    l_rank                NUMERIC,
    w_pct_rank            NUMERIC,
    min_rank              NUMERIC,
    fgm_rank              NUMERIC,
    fga_rank              NUMERIC,
    fg_pct_rank           NUMERIC,
    fg3m_rank             NUMERIC,
    fg3a_rank             NUMERIC,
    fg3_pct_rank          NUMERIC,
    ftm_rank              NUMERIC,
    fta_rank              NUMERIC,
    ft_pct_rank           NUMERIC,
    oreb_rank             NUMERIC,
    dreb_rank             NUMERIC,
    reb_rank              NUMERIC,
    ast_rank              NUMERIC,
    tov_rank              NUMERIC,
    stl_rank              NUMERIC,
    blk_rank              NUMERIC,
    blka_rank             NUMERIC,
    pf_rank               NUMERIC,
    pfd_rank              NUMERIC,
    pts_rank              NUMERIC,
    plus_minus_rank       NUMERIC,
    nba_fantasy_pts_rank  NUMERIC,
    dd2_rank              NUMERIC,
    td3_rank              NUMERIC,
    wnba_fantasy_pts_rank NUMERIC,

    PRIMARY KEY (game_id, player_id)
);

-- ── raw.player_adv ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS raw.player_adv (
    game_id               TEXT        NOT NULL,
    player_id             BIGINT      NOT NULL,
    fetched_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    season_year           TEXT,
    player_name           TEXT,
    nickname              TEXT,
    team_id               BIGINT,
    team_abbreviation     TEXT,
    team_name             TEXT,
    game_date             TEXT,
    matchup               TEXT,
    wl                    TEXT,
    available_flag        TEXT,
    min                   NUMERIC,
    -- advanced metrics
    e_off_rating          NUMERIC,
    off_rating            NUMERIC,
    e_def_rating          NUMERIC,
    def_rating            NUMERIC,
    e_net_rating          NUMERIC,
    net_rating            NUMERIC,
    ast_pct               NUMERIC,
    ast_tov               NUMERIC,
    ast_ratio             NUMERIC,
    oreb_pct              NUMERIC,
    dreb_pct              NUMERIC,
    reb_pct               NUMERIC,
    tm_tov_pct            NUMERIC,
    efg_pct               NUMERIC,
    ts_pct                NUMERIC,
    usg_pct               NUMERIC,
    e_usg_pct             NUMERIC,
    e_pace                NUMERIC,
    pace                  NUMERIC,
    pace_per40            NUMERIC,
    poss                  NUMERIC,
    pie                   NUMERIC,
    -- rank columns
    off_rating_rank       NUMERIC,
    def_rating_rank       NUMERIC,
    net_rating_rank       NUMERIC,
    ast_pct_rank          NUMERIC,
    ast_tov_rank          NUMERIC,
    ast_ratio_rank        NUMERIC,
    oreb_pct_rank         NUMERIC,
    dreb_pct_rank         NUMERIC,
    reb_pct_rank          NUMERIC,
    tm_tov_pct_rank       NUMERIC,
    efg_pct_rank          NUMERIC,
    ts_pct_rank           NUMERIC,
    usg_pct_rank          NUMERIC,
    e_usg_pct_rank        NUMERIC,
    e_pace_rank           NUMERIC,
    pace_rank             NUMERIC,
    pace_per40_rank       NUMERIC,
    poss_rank             NUMERIC,
    pie_rank              NUMERIC,

    PRIMARY KEY (game_id, player_id)
);

-- ── raw.team_base ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS raw.team_base (
    game_id               TEXT        NOT NULL,
    team_id               BIGINT      NOT NULL,
    fetched_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    season_year           TEXT,
    team_abbreviation     TEXT,
    team_name             TEXT,
    game_date             TEXT,
    matchup               TEXT,
    wl                    TEXT,
    available_flag        TEXT,
    min                   NUMERIC,
    fgm                   NUMERIC,
    fga                   NUMERIC,
    fg_pct                NUMERIC,
    fg3m                  NUMERIC,
    fg3a                  NUMERIC,
    fg3_pct               NUMERIC,
    ftm                   NUMERIC,
    fta                   NUMERIC,
    ft_pct                NUMERIC,
    oreb                  NUMERIC,
    dreb                  NUMERIC,
    reb                   NUMERIC,
    ast                   NUMERIC,
    tov                   NUMERIC,
    stl                   NUMERIC,
    blk                   NUMERIC,
    blka                  NUMERIC,
    pf                    NUMERIC,
    pfd                   NUMERIC,
    pts                   NUMERIC,
    plus_minus            NUMERIC,
    gp_rank               NUMERIC,
    w_rank                NUMERIC,
    l_rank                NUMERIC,
    w_pct_rank            NUMERIC,
    min_rank              NUMERIC,
    fgm_rank              NUMERIC,
    fga_rank              NUMERIC,
    fg_pct_rank           NUMERIC,
    fg3m_rank             NUMERIC,
    fg3a_rank             NUMERIC,
    fg3_pct_rank          NUMERIC,
    ftm_rank              NUMERIC,
    fta_rank              NUMERIC,
    ft_pct_rank           NUMERIC,
    oreb_rank             NUMERIC,
    dreb_rank             NUMERIC,
    reb_rank              NUMERIC,
    ast_rank              NUMERIC,
    tov_rank              NUMERIC,
    stl_rank              NUMERIC,
    blk_rank              NUMERIC,
    blka_rank             NUMERIC,
    pf_rank               NUMERIC,
    pfd_rank              NUMERIC,
    pts_rank              NUMERIC,
    plus_minus_rank       NUMERIC,

    PRIMARY KEY (game_id, team_id)
);

-- ── raw.team_adv ──────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS raw.team_adv (
    game_id               TEXT        NOT NULL,
    team_id               BIGINT      NOT NULL,
    fetched_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    season_year           TEXT,
    team_abbreviation     TEXT,
    team_name             TEXT,
    game_date             TEXT,
    matchup               TEXT,
    wl                    TEXT,
    available_flag        TEXT,
    min                   NUMERIC,
    e_off_rating          NUMERIC,
    off_rating            NUMERIC,
    e_def_rating          NUMERIC,
    def_rating            NUMERIC,
    e_net_rating          NUMERIC,
    net_rating            NUMERIC,
    ast_pct               NUMERIC,
    ast_tov               NUMERIC,
    ast_ratio             NUMERIC,
    oreb_pct              NUMERIC,
    dreb_pct              NUMERIC,
    reb_pct               NUMERIC,
    tm_tov_pct            NUMERIC,
    efg_pct               NUMERIC,
    ts_pct                NUMERIC,
    usg_pct               NUMERIC,
    e_usg_pct             NUMERIC,
    e_pace                NUMERIC,
    pace                  NUMERIC,
    pace_per40            NUMERIC,
    poss                  NUMERIC,
    pie                   NUMERIC,
    off_rating_rank       NUMERIC,
    def_rating_rank       NUMERIC,
    net_rating_rank       NUMERIC,
    ast_pct_rank          NUMERIC,
    ast_tov_rank          NUMERIC,
    ast_ratio_rank        NUMERIC,
    oreb_pct_rank         NUMERIC,
    dreb_pct_rank         NUMERIC,
    reb_pct_rank          NUMERIC,
    tm_tov_pct_rank       NUMERIC,
    efg_pct_rank          NUMERIC,
    ts_pct_rank           NUMERIC,
    usg_pct_rank          NUMERIC,
    e_usg_pct_rank        NUMERIC,
    e_pace_rank           NUMERIC,
    pace_rank             NUMERIC,
    pace_per40_rank       NUMERIC,
    poss_rank             NUMERIC,
    pie_rank              NUMERIC,

    PRIMARY KEY (game_id, team_id)
);

-- ── raw.start_positions ───────────────────────────────────────────────────────
-- Source: BoxScorePlayerTrackV3 — one row per player per game.
-- start_position is '' (empty string) for bench players, a letter for starters.

CREATE TABLE IF NOT EXISTS raw.start_positions (
    game_id        TEXT        NOT NULL,
    player_id      BIGINT      NOT NULL,
    fetched_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    start_position TEXT,
    spd            NUMERIC,
    dist           NUMERIC,
    orbc           NUMERIC,
    drbc           NUMERIC,
    rbc            NUMERIC,
    tchs           NUMERIC,
    sast           NUMERIC,
    ftast          NUMERIC,
    pass           NUMERIC,
    cfgm           NUMERIC,
    cfga           NUMERIC,
    cfg_pct        NUMERIC,
    ufgm           NUMERIC,
    ufga           NUMERIC,
    ufg_pct        NUMERIC,
    dfgm           NUMERIC,
    dfga           NUMERIC,
    dfg_pct        NUMERIC,

    PRIMARY KEY (game_id, player_id)
);
