projectedStartingFive = {
    "ATL": ["Jalen Johnson", "Nickeil Alexander-Walker", "Dyson Daniels", "Onyeka Okongwu", "Zaccharie Risacher"],
    "BKN": ["Michael Porter", "Nic Claxton", "Terance Mann", "Noah Clowney", "Egor Demin"],
    "BOS": ["Jaylen Brown", "Derrick White", "Neemias Queta", "Payton Pritchard", "Jordan Walsh"],
    "CHA": ["LaMelo Ball", "Kon Knueppel", "Moussa Diabate", "Sion James", "Miles Bridges"],
    "CHI": ["Matas Buzelis", "Isaac Okoro", "Nikola Vucevic", "Tre Jones", "Kevin Huerter"],
    "CLE": ["Sam Merrill", "Donovan Mitchell", "Evan Mobley", "De'Andre Hunter", "Jarrett Allen"],
    "DAL": ["Cooper Flagg", "Max Christie", "Daniel Gafford", "Brandon Williams", "Klay Thompson"],
    "DEN": ["Jamal Murray", "Nikola Jokic", "Aaron Gordon"],
    "DET": ["Daniss Jenkins", "Paul Reed", "Ronald Holland", "Javonte Green", "Duncan Robinson"],
    "GSW": ["Moses Moody", "Jimmy Butler", "Draymond Green", "Will Richard", "Stephen Curry"],
    "HOU": ["Amen Thompson", "Kevin Durant", "Alperen Sengun", "Josh Okogie", "Jabari Smith"],
    "IND": ["Andrew Nembhard", "Tony Bradley", "Pascal Siakam", "Jeremiah Robinson-Earl", "Tyrese Haliburton"],
    "LAC": ["Bradley Beal", "Ivica Zubac", "John Collins", "Kris Dunn", "James Harden"],
    "LAL": ["Luka Doncic", "Austin Reaves", "Marcus Smart", "Rui Hachimura", "Deandre Ayton"],
    "MEM": ["Jaren Jackson", "Jock Landale", "Javon Small", "Vince Williams", "Jaylen Wells"],
    "MIA": ["Andrew Wiggins", "Pelle Larsson", "Davion Mitchell", "Kel'el Ware", "Norman Powell"],
    "MIL": ["Ryan Rollins", "Giannis Antetokounmpo", "AJ Green", "Myles Turner", "Kyle Kuzma"],
    "MIN": ["Julius Randle", "Donte DiVincenzo", "Rudy Gobert", "Anthony Edwards", "Jaden McDaniels"],
    "NOP": ["Trey Murphy", "Saddiq Bey", "Jeremiah Fears", "Herbert Jones", "Kevon Looney"],
    "NYK": ["Miles McBride", "Mitchell Robinson", "Mikal Bridges", "OG Anunoby", "Karl-Anthony Towns"],
    "OKC": ["Shai Gilgeous-Alexander", "Ajay Mitchell", "Cason Wallace", "Chet Holmgren", "Thomas Sorber"],
    "ORL": ["Jalen Suggs", "Desmond Bane", "Wendell Carter", "Tristan da Silva", "Franz Wagner"],
    "PHI": ["Tyrese Maxey", "Trendon Watford", "Kelly Oubre", "Andre Drummond", "VJ Edgecombe"],
    "PHX": ["Devin Booker", "Dillon Brooks", "Royce O'Neale", "Grayson Allen", "Nick Richards"],
    "POR": ["Shaedon Sharpe", "Deni Avdija", "Jrue Holiday", "Damian Lillard", "Donovan Clingan"],
    "SAC": ["DeMar DeRozan", "Russell Westbrook", "Zach LaVine", "Domantas Sabonis", "Precious Achiuwa"],
    "SAS": ["Harrison Barnes", "De'Aaron Fox", "Devin Vassell", "Victor Wembanyama", "Stephon Castle"],
    "TOR": ["RJ Barrett", "Scottie Barnes", "Jakob Poeltl", "Immanuel Quickley", "Brandon Ingram"],
    "UTA": ["Ace Bailey", "Keyonte George", "Jusuf Nurkic", "Walker Kessler", "Lauri Markkanen"],
    "WAS": ["Alex Sarr", "CJ McCollum", "Khris Middleton", "Tre Johnson", "Kyshawn George"],
}

mainStartingFive = {
    "ATL": ["Nickeil Alexander-Walker", "Dyson Daniels", "Zaccharie Risacher", "Jalen Johnson", "Kristaps Porzingis"],
    "BOS": ["Derrick White", "Payton Pritchard", "Jaylen Brown", "Josh Minott", "Neemias Queta"],
    "BKN": ["Tyrese Martin", "Cam Thomas", "Terance Mann", "Michael Porter Jr.", "Nic Claxton"],
    "CHA": ["LaMelo Ball", "Collin Sexton", "Brandon Miller", "Miles Bridges", "Ryan Kalkbrenner"],
    "CHI": ["Josh Giddey", "Coby White", "Isaac Okoro", "Matas Buzelis", "Nikola Vucevic"],
    "CLE": ["Darius Garland", "Donovan Mitchell", "De'Andre Hunter", "Evan Mobley", "Jarrett Allen"],
    "DAL": ["Cooper Flagg", "Klay Thompson", "P.J. Washington", "Anthony Davis", "Dereck Lively II"],
    "DEN": ["Jamal Murray", "Christian Braun", "Cameron Johnson", "Aaron Gordon", "Nikola Jokic"],
    "DET": ["Cade Cunningham", "Duncan Robinson", "Ausar Thompson", "Tobias Harris", "Jalen Duren"],
    "GSW": ["Stephen Curry", "Jimmy Butler III", "Jonathan Kuminga", "Draymond Green", "Quinten Post"],
    "HOU": ["Amen Thompson", "Josh Okogie", "Kevin Durant", "Jabari Smith Jr.", "Alperen Sengun"],
    "IND": ["Andrew Nembhard", "Bennedict Mathurin", "Aaron Nesmith", "Pascal Siakam", "Isaiah Jackson"],
    "LAC": ["James Harden", "Bradley Beal", "Kawhi Leonard", "Derrick Jones Jr.", "Ivica Zubac"],
    "LAL": ["Luka Doncic", "Austin Reaves", "Marcus Smart", "Rui Hachimura", "Deandre Ayton"],
    "MEM": ["Ja Morant", "Kentavious Caldwell-Pope", "Jaylen Wells", "Jaren Jackson Jr.", "Jock Landale"],
    "MIA": ["Davion Mitchell", "Norman Powell", "Andrew Wiggins", "Bam Adebayo", "Kel'el Ware"],
    "MIL": ["Ryan Rollins", "AJ Green", "Gary Trent Jr.", "Giannis Antetokounmpo", "Myles Turner"],
    "MIN": ["Donte DiVincenzo", "Anthony Edwards", "Jaden McDaniels", "Julius Randle", "Rudy Gobert"],
    "NOP": ["Jeremiah Fears", "Trey Murphy III", "Herbert Jones", "Zion Williamson", "Yves Missi"],
    "NYK": ["Jalen Brunson", "Mikal Bridges", "OG Anunoby", "Karl-Anthony Towns", "Mitchell Robinson"],
    "OKC": ["Shai Gilgeous-Alexander", "Luguentz Dort", "Jaylin Williams", "Chet Holmgren", "Isaiah Hartenstein"],
    "ORL": ["Jalen Suggs", "Desmond Bane", "Franz Wagner", "Paolo Banchero", "Wendell Carter Jr."],
    "PHI": ["Tyrese Maxey", "VJ Edgecombe", "Kelly Oubre Jr.", "Paul George", "Joel Embiid"],
    "PHX": ["Devin Booker", "Jalen Green", "Dillon Brooks", "Ryan Dunn", "Mark Williams"],
    "POR": ["Jrue Holiday", "Shaedon Sharpe", "Toumani Camara", "Deni Avdija", "Donovan Clingan"],
    "SAC": ["Dennis Schroder", "Zach LaVine", "DeMar DeRozan", "Domantas Sabonis", "Dylan Cardwell"],
    "SAS": ["De'Aaron Fox", "Stephon Castle", "Devin Vassell", "Harrison Barnes", "Victor Wembanyama"],
    "TOR": ["Immanuel Quickley", "RJ Barrett", "Brandon Ingram", "Scottie Barnes", "Jakob Poeltl"],
    "UTA": ["Isaiah Collier", "Svi Mykhailiuk", "Lauri Markkanen", "Kyle Filipowski", "Walker Kessler"],
    "WAS": ["CJ McCollum", "Kyshawn George", "Khris Middleton", "Bilal Coulibaly", "Alex Sarr"]
}

teamStarPlayer = {
    "OKC": "Shai Gilgeous-Alexander", 
    "DEN": 'Nikola Jokic', 
    "NYK": 'Jalen Brunson', 
    "CLE": "Donovan Mitchell",
    "ORL": "Paolo Banchero", 
    "MIN": "Anthony Edwards", 
    "GSW": "Stephen Curry", 
    "LAL": 'Luka Doncic', 
    "HOU": "Kevin Durant",
    "SAS": "Victor Wembanyama", 
    "LAC": "Kawhi Leonard", 
    "DET": "Cade Cunningham",
    "ATL": "Trae Young",
    "SAC": "Zach LaVine", 
    "DAL": "Anthony Davis",
    "MIA": "Bam Adebayo",
    "TOR": "Scottie Barnes",
    "MEM": "Ja Morant",
    "PHI": "Tyrese Maxey",
    "BOS": "Jaylen Brown",
    "IND": "Pascal Siakam",
    "PHX": "Devin Booker",
    "MIL": "Giannis Antetokounmpo",
    "NOP": "Zion Williamson",
    "POR": "Deni Avdija",
    "CHI": "Josh Giddey",
    "UTA": "Lauri Markkanen",
    "CHA": "LaMelo Ball",
    "BKN": "Cam Thomas",
    "WAS": "Keyshawn George"
}