projectedStartingFive = {
    "ATL": ["Jalen Johnson", "Dyson Daniels", "Zaccharie Risacher", "Kristaps Porzingis", "Nickeil Alexander-Walker"],
    "BKN": ["Noah Clowney", "Terance Mann", "Nic Claxton", "Egor Demin", "Michael Porter"],
    "BOS": ["Jaylen Brown", "Neemias Queta", "Derrick White", "Jordan Walsh", "Payton Pritchard"],
    "CHA": ["Miles Bridges", "Ryan Kalkbrenner", "Sion James", "LaMelo Ball", "Kon Knueppel"],
    "CHI": ["Isaac Okoro", "Coby White", "Matas Buzelis", "Nikola Vucevic", "Josh Giddey"],
    "CLE": ["Nae'Qwan Tomlin", "Donovan Mitchell", "Evan Mobley", "Jarrett Allen", "De'Andre Hunter"],
    "DAL": ["Caleb Martin", "Daniel Gafford", "Max Christie", "P.J. Washington", "Naji Marshall"],
    "DEN": ["Jamal Murray", "Zeke Nnaji", "Cameron Johnson", "Peyton Watson", "Nikola Jokić"],
    "DET": ["Cade Cunningham", "Tobias Harris", "Jalen Duren", "Caris LeVert", "Duncan Robinson"],
    "GSW": ["Will Richard", "Moses Moody", "Gui Santos", "Brandin Podziemski", "Trayce Jackson-Davis"],
    "HOU": ["Kevin Durant", "Jabari Smith", "Steven Adams", "Alperen Sengun", "Amen Thompson"],
    "IND": ["Tyrese Haliburton", "Pascal Siakam", "Bennedict Mathurin", "Ben Sheppard", "Andrew Nembhard"],
    "LAC": ["James Harden", "Ivica Zubac", "John Collins", "Kris Dunn", "Kawhi Leonard"],
    "LAL": ["Austin Reaves", "Luka Doncic", "Rui Hachimura", "Deandre Ayton", "LeBron James"],
    "MEM": ["Santi Aldama", "Zach Edey", "Jaren Jackson", "Vince Williams", "Jaylen Wells"],
    "MIA": ["Andrew Wiggins", "Davion Mitchell", "Bam Adebayo", "Pelle Larsson", "Norman Powell"],
    "MIL": ["AJ Green", "Ryan Rollins", "Kyle Kuzma", "Myles Turner", "Bobby Portis"],
    "MIN": ["Rudy Gobert", "Anthony Edwards", "Donte DiVincenzo", "Mike Conley", "Julius Randle"],
    "NOP": ["Jeremiah Fears", "Herbert Jones", "Zion Williamson", "Trey Murphy", "Derik Queen"],
    "NYK": ["Karl-Anthony Towns", "Mitchell Robinson", "Landry Shamet", "Mikal Bridges"],
    "OKC": ["Thomas Sorber", "Luguentz Dort", "Isaiah Hartenstein", "Chet Holmgren", "Cason Wallace"],
    "ORL": ["Jalen Suggs", "Franz Wagner", "Wendell Carter", "Tristan da Silva", "Desmond Bane"],
    "PHI": ["Adem Bona", "Tyrese Maxey", "Joel Embiid", "Andre Drummond", "Justin Edwards"],
    "PHX": ["Mark Williams", "Devin Booker", "Dillon Brooks", "Ryan Dunn", "Royce O'Neale"],
    "POR": ["Deni Avdija", "Toumani Camara", "Kris Murray", "Caleb Love", "Donovan Clingan"],
    "SAC": ["Precious Achiuwa", "Zach LaVine", "Drew Eubanks", "DeMar DeRozan", "Russell Westbrook"],
    "SAS": ["De'Aaron Fox", "Jordan McLaughlin", "Dylan Harper", "Harrison Barnes", "Devin Vassell"],
    "TOR": ["Immanuel Quickley", "Brandon Ingram", "RJ Barrett", "Jakob Poeltl", "Scottie Barnes"],
    "UTA": ["Keyonte George", "Svi Mykhailiuk", "Walker Kessler", "Lauri Markkanen", "Ace Bailey"],
    "WAS": ["Kyshawn George", "Marvin Bagley", "CJ McCollum", "Khris Middleton", "Bilal Coulibaly"],
}

mainStartingFive = {
    "ATL": ["Nickeil Alexander-Walker", "Dyson Daniels", "Zaccharie Risacher", "Jalen Johnson", "Kristaps Porziņģis"],
    "BOS": ["Derrick White", "Payton Pritchard", "Jaylen Brown", "Jordan Walsh", "Neemias Queta"],
    "BKN": ["Egor Demin", "Noah Clowney", "Terance Mann", "Michael Porter Jr.", "Nic Claxton"],
    "CHA": ["LaMelo Ball", "Kon Knueppel", "Brandon Miller", "Miles Bridges", "Ryan Kalkbrenner"],
    "CHI": ["Josh Giddey", "Coby White", "Isaac Okoro", "Matas Buzelis", "Nikola Vučević"],
    "CLE": ["Darius Garland", "Donovan Mitchell", "De'Andre Hunter", "Evan Mobley", "Jarrett Allen"],
    "DAL": ["Brondon Williams", "Max Christie", "P.J. Washington", "Cooper Flagg", "Daniel Gafford"],
    "DEN": ["Jamal Murray", "Peyton Watson", "Cameron Johnson", "Aaron Gordon", "Nikola Jokić"],
    "DET": ["Cade Cunningham", "Duncan Robinson", "Ausar Thompson", "Tobias Harris", "Jalen Duren"],
    "GSW": ["Stephen Curry", "Jimmy Butler III", "Will Richard", "Draymond Green", "Moses Moody"],
    "HOU": ["Amen Thompson", "Josh Okogie", "Kevin Durant", "Jabari Smith Jr.", "Alperen Sengun"],
    "IND": ["Andrew Nembhard", "Bennedict Mathurin", "Jarace Walker", "Pascal Siakam", "Isaiah Jackson"],
    "LAC": ["James Harden", "Kriss Dunn", "Kawhi Leonard", "John Collins", "Ivica Zubac"],
    "LAL": ["Luka Dončić", "Austin Reaves", "LeBron James", "Rui Hachimura", "Deandre Ayton"],
    "MEM": ["Ja Morant", "Cedric Coward", "Jaylen Wells", "Jaren Jackson Jr.", "Zach Edey"],
    "MIA": ["Davion Mitchell", "Norman Powell", "Pelle Larsson", "Andrew Wiggins", "Bam Adebayo"],
    "MIL": ["Ryan Rollins", "AJ Green", "Kyle Kuzma", "Giannis Antetokounmpo", "Myles Turner"],
    "MIN": ["Donte DiVincenzo", "Anthony Edwards", "Jaden McDaniels", "Julius Randle", "Rudy Gobert"],
    "NOP": ["Jeremiah Fears", "Trey Murphy III", "Herbert Jones", "Zion Williamson", "Derik Queen"],
    "NYK": ["Jalen Brunson", "Mikal Bridges", "OG Anunoby", "Karl-Anthony Towns", "Mitchell Robinson"],
    "OKC": ["Shai Gilgeous-Alexander", "Cason Wallace", "Luguentz Dort", "Chet Holmgren", "Isaiah Hartenstein"],
    "ORL": ["Jalen Suggs", "Desmond Bane", "Franz Wagner", "Paolo Banchero", "Wendell Carter Jr."],
    "PHI": ["Tyrese Maxey", "VJ Edgecombe", "Kelly Oubre Jr.", "Paul George", "Joel Embiid"],
    "PHX": ["Devin Booker", "Grayson Allen", "Dillon Brooks", "Royce O'Neale", "Mark Williams"],
    "POR": ["Jrue Holiday", "Shaedon Sharpe", "Toumani Camara", "Deni Avdija", "Donovan Clingan"],
    "SAC": ["Russell Westbrook", "Zach LaVine", "DeMar DeRozan", "Keegan Murray", "Domantas Sabonis"],
    "SAS": ["De'Aaron Fox", "Stephon Castle", "Devin Vassell", "Harrison Barnes", "Victor Wembanyama"],
    "TOR": ["Immanuel Quickley", "Brandon Ingram", "RJ Barrett", "Scottie Barnes", "Jakob Poeltl"],
    "UTA": ["Keyonte George", "Svi Mykhailiuk", "Ace Bailey", "Lauri Markkanen", "Jusuf Nurkic"],
    "WAS": ["CJ McCollum", "Kyshawn George", "Bilal Coulibaly", "Khris Middleton", "Alex Sarr"]
}

teamStarPlayer = {
    "OKC": "Shai Gilgeous-Alexander", 
    "DEN": 'Nikola Jokić', 
    "NYK": 'Jalen Brunson', 
    "CLE": "Donovan Mitchell",
    "ORL": "Paolo Banchero", 
    "MIN": "Anthony Edwards", 
    "GSW": "Stephen Curry", 
    "LAL": 'Luka Dončić', 
    "HOU": "Alperen Sengun",
    "SAS": "Victor Wembanyama", 
    "LAC": "Kawhi Leonard", 
    "DET": "Cade Cunningham",
    "ATL": "Jalen Johnson",
    "SAC": "Zach LaVine", 
    "DAL": "Anthony Davis",
    "MIA": "Bam Adebayo",
    "TOR": "Scottie Barnes",
    "MEM": "Ja Morant",
    "PHI": "Tyrese Maxey",
    "BOS": "Jaylen Brown",
    "IND": "Pascal Siakam",
    "PHX": "Devin Booker",
    "MIL": "Giannis Antetokounmpo",
    "NOP": "Zion Williamson",
    "POR": "Deni Avdija",
    "CHI": "Josh Giddey",
    "UTA": "Lauri Markkanen",
    "CHA": "LaMelo Ball",
    "BKN": "Cam Thomas",
    "WAS": "Keyshawn George"
}

# Name mapping dictionary to handle special characters in player names
nameDict = {
    'Nikola Jokic': 'Nikola Jokić',
    'Luka Doncic': 'Luka Dončić',
    'Nikola Vucevic': 'Nikola Vučević',
    'Jonas Valanciunas': 'Jonas Valančiūnas',
    'Dennis Schroder': 'Dennis Schröder',
    'Kristaps Porzingis': 'Kristaps Porziņģis',
    'Bogdan Bogdanovic': 'Bogdan Bogdanović',
    'Dario Saric': 'Dario Šarić',
    'Nikola Jovic': 'Nikola Jović',
    'Vlatko Cancar': 'Vlatko Čančar',
}
