projectedStartingFive = {
    "ATL": ["Zaccharie Risacher", "Dyson Daniels", "Kristaps Porzingis", "Nickeil Alexander-Walker", "Jalen Johnson"],
    "BKN": ["Egor Demin", "Michael Porter", "Noah Clowney", "Nic Claxton", "Terance Mann"],
    "BOS": ["Payton Pritchard", "Derrick White", "Jordan Walsh", "Jaylen Brown", "Neemias Queta"],
    "CHA": ["Miles Bridges", "Ryan Kalkbrenner", "Sion James", "LaMelo Ball", "Kon Knueppel"],
    "CHI": ["Nikola Vučević", "Josh Giddey", "Ayo Dosunmu", "Isaac Okoro", "Matas Buzelis"],
    "CLE": ["Darius Garland", "Donovan Mitchell", "De'Andre Hunter", "Jaylon Tyson", "Evan Mobley"],
    "DAL": ["Brandon Williams", "Max Christie", "Cooper Flagg", "P.J. Washington", "Daniel Gafford"],
    "DEN": ["Jamal Murray", "Nikola Jokić", "Aaron Gordon", "Cameron Johnson", "Peyton Watson"],
    "DET": ["Cade Cunningham", "Tobias Harris", "Jalen Duren", "Caris LeVert", "Duncan Robinson"],
    "GSW": ["Draymond Green", "Buddy Hield", "Moses Moody", "Jimmy Butler", "Stephen Curry"],
    "HOU": ["Jabari Smith", "Kevin Durant", "Amen Thompson", "Alperen Sengun", "Steven Adams"],
    "IND": ["Andrew Nembhard", "Ben Sheppard", "Isaiah Jackson", "Bennedict Mathurin", "Tyrese Haliburton"],
    "LAC": ["Jordan Miller", "Ivica Zubac", "James Harden", "John Collins", "Kawhi Leonard"],
    "LAL": ["Austin Reaves", "Luka Doncic", "Rui Hachimura", "Deandre Ayton", "LeBron James"],
    "MEM": ["Santi Aldama", "Jaylen Wells", "Vince Williams", "Zach Edey", "Jaren Jackson"],
    "MIA": ["Bam Adebayo", "Davion Mitchell", "Kel'el Ware", "Pelle Larsson", "Norman Powell"],
    "MIL": ["Bobby Portis", "Kyle Kuzma", "AJ Green", "Ryan Rollins", "Myles Turner"],
    "MIN": ["Julius Randle", "Rudy Gobert", "Donte DiVincenzo", "Jaden McDaniels", "Anthony Edwards"],
    "NOP": ["Trey Murphy", "Derik Queen", "Zion Williamson", "Jeremiah Fears", "Herbert Jones"],
    "NYK": ["Karl-Anthony Towns", "Mitchell Robinson", "Landry Shamet", "Mikal Bridges"],
    "OKC": ["Cason Wallace", "Thomas Sorber", "Isaiah Hartenstein", "Luguentz Dort", "Chet Holmgren"],
    "ORL": ["Franz Wagner", "Tristan da Silva", "Jalen Suggs", "Wendell Carter", "Desmond Bane"],
    "PHI": ["Paul George", "Andre Drummond", "Tyrese Maxey", "Adem Bona", "Joel Embiid"],
    "PHX": ["Royce O'Neale", "Devin Booker", "Ryan Dunn", "Dillon Brooks", "Mark Williams"],
    "POR": ["Donovan Clingan", "Sidy Cissoko", "Deni Avdija", "Damian Lillard", "Toumani Camara"],
    "SAC": ["Russell Westbrook", "DeMar DeRozan", "Precious Achiuwa", "Drew Eubanks", "Zach LaVine"],
    "SAS": ["Dylan Harper", "Julian Champagnie", "Luke Kornet", "De'Aaron Fox", "Harrison Barnes"],
    "TOR": ["Brandon Ingram", "Scottie Barnes", "RJ Barrett", "Immanuel Quickley", "Jakob Poeltl"],
    "UTA": ["Keyonte George", "Ace Bailey", "Lauri Markkanen", "Svi Mykhailiuk", "Walker Kessler"],
    "WAS": ["Tristan Vukcevic", "Bilal Coulibaly", "CJ McCollum", "Khris Middleton", "Kyshawn George"],
}

mainStartingFive = {
    "ATL": ["Nickeil Alexander-Walker", "Dyson Daniels", "Zaccharie Risacher", "Jalen Johnson", "Kristaps Porziņģis"],
    "BOS": ["Derrick White", "Payton Pritchard", "Jaylen Brown", "Jordan Walsh", "Neemias Queta"],
    "BKN": ["Egor Demin", "Noah Clowney", "Terance Mann", "Michael Porter Jr.", "Nic Claxton"],
    "CHA": ["LaMelo Ball", "Kon Knueppel", "Brandon Miller", "Miles Bridges", "Ryan Kalkbrenner"],
    "CHI": ["Josh Giddey", "Coby White", "Isaac Okoro", "Matas Buzelis", "Nikola Vučević"],
    "CLE": ["Darius Garland", "Donovan Mitchell", "De'Andre Hunter", "Evan Mobley", "Jarrett Allen"],
    "DAL": ["Brondon Williams", "Max Christie", "P.J. Washington", "Cooper Flagg", "Daniel Gafford"],
    "DEN": ["Jamal Murray", "Peyton Watson", "Cameron Johnson", "Aaron Gordon", "Nikola Jokić"],
    "DET": ["Cade Cunningham", "Duncan Robinson", "Ausar Thompson", "Tobias Harris", "Jalen Duren"],
    "GSW": ["Stephen Curry", "Jimmy Butler III", "Will Richard", "Draymond Green", "Moses Moody"],
    "HOU": ["Amen Thompson", "Josh Okogie", "Kevin Durant", "Jabari Smith Jr.", "Alperen Sengun"],
    "IND": ["Andrew Nembhard", "Bennedict Mathurin", "Ben Sheppard", "Pascal Siakam", "Isaiah Jackson"],
    "LAC": ["James Harden", "Kriss Dunn", "Kawhi Leonard", "John Collins", "Ivica Zubac"],
    "LAL": ["Luka Dončić", "Austin Reaves", "LeBron James", "Rui Hachimura", "Deandre Ayton"],
    "MEM": ["Ja Morant", "Cedric Coward", "Jaylen Wells", "Jaren Jackson Jr.", "Zach Edey"],
    "MIA": ["Davion Mitchell", "Norman Powell", "Pelle Larsson", "Andrew Wiggins", "Bam Adebayo"],
    "MIL": ["Ryan Rollins", "AJ Green", "Kyle Kuzma", "Giannis Antetokounmpo", "Myles Turner"],
    "MIN": ["Donte DiVincenzo", "Anthony Edwards", "Jaden McDaniels", "Julius Randle", "Rudy Gobert"],
    "NOP": ["Jeremiah Fears", "Trey Murphy III", "Herbert Jones", "Zion Williamson", "Derik Queen"],
    "NYK": ["Jalen Brunson", "Mikal Bridges", "OG Anunoby", "Karl-Anthony Towns", "Mitchell Robinson"],
    "OKC": ["Shai Gilgeous-Alexander", "Cason Wallace", "Luguentz Dort", "Chet Holmgren", "Isaiah Hartenstein"],
    "ORL": ["Jalen Suggs", "Desmond Bane", "Franz Wagner", "Paolo Banchero", "Wendell Carter Jr."],
    "PHI": ["Tyrese Maxey", "VJ Edgecombe", "Kelly Oubre Jr.", "Paul George", "Joel Embiid"],
    "PHX": ["Devin Booker", "Grayson Allen", "Dillon Brooks", "Royce O'Neale", "Mark Williams"],
    "POR": ["Jrue Holiday", "Shaedon Sharpe", "Toumani Camara", "Deni Avdija", "Donovan Clingan"],
    "SAC": ["Russell Westbrook", "Zach LaVine", "DeMar DeRozan", "Keegan Murray", "Domantas Sabonis"],
    "SAS": ["De'Aaron Fox", "Stephon Castle", "Devin Vassell", "Harrison Barnes", "Victor Wembanyama"],
    "TOR": ["Immanuel Quickley", "Brandon Ingram", "RJ Barrett", "Scottie Barnes", "Jakob Poeltl"],
    "UTA": ["Keyonte George", "Svi Mykhailiuk", "Ace Bailey", "Lauri Markkanen", "Jusuf Nurkic"],
    "WAS": ["CJ McCollum", "Kyshawn George", "Bilal Coulibaly", "Khris Middleton", "Alex Sarr"]
}

teamStarPlayer = {
    "OKC": "Shai Gilgeous-Alexander", 
    "DEN": 'Nikola Jokić', 
    "NYK": 'Jalen Brunson', 
    "CLE": "Donovan Mitchell",
    "ORL": "Paolo Banchero", 
    "MIN": "Julius Randle", 
    "GSW": "Stephen Curry", 
    "LAL": 'Luka Dončić', 
    "HOU": "Alperen Sengun",
    "SAS": "Victor Wembanyama", 
    "LAC": "James Harden", 
    "DET": "Cade Cunningham",
    "ATL": "Jalen Johnson",
    "SAC": "Zach LaVine", 
    "DAL": "D'Angelo Russell",
    "MIA": "Norman Powell",
    "TOR": "Brandon Ingram",
    "MEM": "Cedric Coward",
    "PHI": "Tyrese Maxey",
    "BOS": "Jaylen Brown",
    "IND": "Pascal Siakam",
    "PHX": "Devin Booker",
    "MIL": "Giannis Antetokounmpo",
    "NOP": "Trey Murphy III",
    "POR": "Deni Avdija",
    "CHI": "Ayo Dosunmu",
    "UTA": "Lauri Markkanen",
    "CHA": "LaMelo Ball",
    "BKN": "Michael Porter Jr.",
    "WAS": "Alex Sarr"
}

# Name mapping dictionary to handle special characters in player names
nameDict = {
    'Nikola Jokic': 'Nikola Jokić',
    'Luka Doncic': 'Luka Dončić',
    'Nikola Vucevic': 'Nikola Vučević',
    'Jonas Valanciunas': 'Jonas Valančiūnas',
    'Dennis Schroder': 'Dennis Schröder',
    'Kristaps Porzingis': 'Kristaps Porziņģis',
    'Bogdan Bogdanovic': 'Bogdan Bogdanović',
    'Dario Saric': 'Dario Šarić',
    'Nikola Jovic': 'Nikola Jović',
    'Vlatko Cancar': 'Vlatko Čančar',
}
