projectedStartingFive = {
    "ATL": ["CJ McCollum", "Dyson Daniels", "Nickeil Alexander-Walker", "Onyeka Okongwu", "Jalen Johnson"],
    "BKN": ["Chaney Johnson", "Drake Powell", "E.J. Liddell", "Nolan Traore", "Jalen Wilson"],
    "BOS": ["Jaylen Brown", "Derrick White", "Sam Hauser", "Neemias Queta", "Jayson Tatum"],
    "CHA": ["Brandon Miller", "Miles Bridges", "Moussa Diabaté", "Kon Knueppel", "LaMelo Ball"],
    "CHI": ["Guerschon Yabusele", "Leonard Miller", "Isaac Okoro", "Tre Jones"],
    "CLE": ["Dennis Schröder", "Jarrett Allen", "Keon Ellis", "Sam Merrill", "Evan Mobley"],
    "DAL": ["Cooper Flagg", "Khris Middleton", "Max Christie", "Naji Marshall"],
    "DEN": ["Nikola Jokić", "Christian Braun", "Aaron Gordon", "Jamal Murray", "Cameron Johnson"],
    "DET": ["Paul Reed", "Kevin Huerter", "Ausar Thompson", "Daniss Jenkins", "Jalen Duren"],
    "GSW": ["Draymond Green", "De'Anthony Melton", "Brandin Podziemski"],
    "HOU": ["Amen Thompson", "Alperen Sengun", "Kevin Durant", "Jabari Smith", "Reed Sheppard"],
    "IND": ["Micah Potter", "Ethan Thompson", "Kobe Brown", "Quenton Jackson"],
    "LAC": ["Kawhi Leonard", "Kris Dunn", "Derrick Jones", "Darius Garland", "Brook Lopez"],
    "LAL": ["Jake LaRavia", "Jarred Vanderbilt", "Luke Kennard", "Deandre Ayton", "Rui Hachimura"],
    "MEM": ["Olivier-Maxence Prosper", "GG Jackson", "Rayan Rupert", "Walter Clayton", "Cedric Coward"],
    "MIA": ["Bam Adebayo", "Andrew Wiggins", "Davion Mitchell", "Norman Powell"],
    "MIL": ["Taurean Prince", "Pete Nance", "AJ Green", "Ousmane Dieng", "Jericho Sims"],
    "MIN": ["Mike Conley", "Rudy Gobert", "Julius Randle", "Ayo Dosunmu", "Donte DiVincenzo"],
    "NOP": ["Jeremiah Fears", "Saddiq Bey", "Herbert Jones", "Zion Williamson"],
    "NYK": ["OG Anunoby", "Mikal Bridges", "Josh Hart", "Karl-Anthony Towns", "Jalen Brunson"],
    "OKC": ["Shai Gilgeous-Alexander", "Isaiah Hartenstein", "Luguentz Dort", "Cason Wallace", "Chet Holmgren"],
    "ORL": ["Wendell Carter", "Jalen Suggs", "Tristan da Silva", "Paolo Banchero", "Desmond Bane"],
    "PHI": ["Paul George", "Kelly Oubre", "Joel Embiid", "Tyrese Maxey", "VJ Edgecombe"],
    "PHX": ["Jordan Goodwin", "Mark Williams", "Jalen Green", "Devin Booker", "Dillon Brooks"],
    "POR": ["Scoot Henderson", "Deni Avdija", "Toumani Camara", "Donovan Clingan", "Jrue Holiday"],
    "SAC": ["Maxime Raynaud", "Precious Achiuwa", "Devin Carter", "Nique Clifford"],
    "SAS": ["Julian Champagnie", "Devin Vassell", "De'Aaron Fox", "Victor Wembanyama", "Stephon Castle"],
    "TOR": ["Scottie Barnes", "Jakob Poeltl", "Brandon Ingram", "RJ Barrett"],
    "UTA": ["Cody Williams", "Oscar Tshiebwe", "Brice Sensabaugh", "John Konchar"],
    "WAS": ["Anthony Gill", "Bilal Coulibaly", "Will Riley", "Bub Carrington"],
}

mainStartingFive = {
    "ATL": ["Nickeil Alexander-Walker", "Dyson Daniels", "Zaccharie Risacher", "Jalen Johnson", "Kristaps Porziņģis"],
    "BOS": ["Derrick White", "Payton Pritchard", "Jaylen Brown", "Jordan Walsh", "Neemias Queta"],
    "BKN": ["Egor Demin", "Noah Clowney", "Terance Mann", "Michael Porter Jr.", "Nic Claxton"],
    "CHA": ["LaMelo Ball", "Kon Knueppel", "Brandon Miller", "Miles Bridges", "Ryan Kalkbrenner"],
    "CHI": ["Josh Giddey", "Coby White", "Isaac Okoro", "Matas Buzelis", "Nikola Vučević"],
    "CLE": ["Darius Garland", "Donovan Mitchell", "De'Andre Hunter", "Evan Mobley", "Jarrett Allen"],
    "DAL": ["Brondon Williams", "Max Christie", "P.J. Washington", "Cooper Flagg", "Daniel Gafford"],
    "DEN": ["Jamal Murray", "Peyton Watson", "Cameron Johnson", "Aaron Gordon", "Nikola Jokić"],
    "DET": ["Cade Cunningham", "Duncan Robinson", "Ausar Thompson", "Tobias Harris", "Jalen Duren"],
    "GSW": ["Stephen Curry", "Jimmy Butler III", "Will Richard", "Draymond Green", "Moses Moody"],
    "HOU": ["Amen Thompson", "Josh Okogie", "Kevin Durant", "Jabari Smith Jr.", "Alperen Sengun"],
    "IND": ["Andrew Nembhard", "Bennedict Mathurin", "Ben Sheppard", "Pascal Siakam", "Isaiah Jackson"],
    "LAC": ["James Harden", "Kriss Dunn", "Kawhi Leonard", "John Collins", "Ivica Zubac"],
    "LAL": ["Luka Dončić", "Austin Reaves", "LeBron James", "Rui Hachimura", "Deandre Ayton"],
    "MEM": ["Ja Morant", "Cedric Coward", "Jaylen Wells", "Jaren Jackson Jr.", "Zach Edey"],
    "MIA": ["Davion Mitchell", "Norman Powell", "Pelle Larsson", "Andrew Wiggins", "Bam Adebayo"],
    "MIL": ["Ryan Rollins", "AJ Green", "Kyle Kuzma", "Giannis Antetokounmpo", "Myles Turner"],
    "MIN": ["Donte DiVincenzo", "Anthony Edwards", "Jaden McDaniels", "Julius Randle", "Rudy Gobert"],
    "NOP": ["Jeremiah Fears", "Trey Murphy III", "Herbert Jones", "Zion Williamson", "Derik Queen"],
    "NYK": ["Jalen Brunson", "Mikal Bridges", "OG Anunoby", "Karl-Anthony Towns", "Mitchell Robinson"],
    "OKC": ["Shai Gilgeous-Alexander", "Cason Wallace", "Luguentz Dort", "Chet Holmgren", "Isaiah Hartenstein"],
    "ORL": ["Jalen Suggs", "Desmond Bane", "Franz Wagner", "Paolo Banchero", "Wendell Carter Jr."],
    "PHI": ["Tyrese Maxey", "VJ Edgecombe", "Kelly Oubre Jr.", "Paul George", "Joel Embiid"],
    "PHX": ["Devin Booker", "Grayson Allen", "Dillon Brooks", "Royce O'Neale", "Mark Williams"],
    "POR": ["Jrue Holiday", "Shaedon Sharpe", "Toumani Camara", "Deni Avdija", "Donovan Clingan"],
    "SAC": ["Russell Westbrook", "Zach LaVine", "DeMar DeRozan", "Keegan Murray", "Domantas Sabonis"],
    "SAS": ["De'Aaron Fox", "Stephon Castle", "Devin Vassell", "Harrison Barnes", "Victor Wembanyama"],
    "TOR": ["Immanuel Quickley", "Brandon Ingram", "RJ Barrett", "Scottie Barnes", "Jakob Poeltl"],
    "UTA": ["Keyonte George", "Svi Mykhailiuk", "Ace Bailey", "Lauri Markkanen", "Jusuf Nurkic"],
    "WAS": ["CJ McCollum", "Kyshawn George", "Bilal Coulibaly", "Khris Middleton", "Alex Sarr"]
}

teamStarPlayer = {
    "OKC": "Shai Gilgeous-Alexander", 
    "DEN": 'Nikola Jokić', 
    "NYK": 'Jalen Brunson', 
    "CLE": "Donovan Mitchell",
    "ORL": "Paolo Banchero", 
    "MIN": "Anthony Edwards", 
    "GSW": "Stephen Curry", 
    "LAL": 'Luka Dončić', 
    "HOU": "Alperen Sengun",
    "SAS": "Victor Wembanyama", 
    "LAC": "Kawhi Leonard", 
    "DET": "Cade Cunningham",
    "ATL": "Jalen Johnson",
    "SAC": "Zach LaVine", 
    "DAL": "Cooper Flagg",
    "MIA": "Norman Powell",
    "TOR": "Brandon Ingram",
    "MEM": "Cedric Coward",
    "PHI": "Tyrese Maxey",
    "BOS": "Jaylen Brown",
    "IND": "Pascal Siakam",
    "PHX": "Devin Booker",
    "MIL": "Giannis Antetokounmpo",
    "NOP": "Zion Williamson",
    "POR": "Deni Avdija",
    "CHI": "Josh Giddey",
    "UTA": "Lauri Markkanen",
    "CHA": "LaMelo Ball",
    "BKN": "Michael Porter Jr.",
    "WAS": "Alex Sarr"
}

# Name mapping dictionary to handle special characters in player names
nameDict = {
    'Nikola Jokic': 'Nikola Jokić',
    'Luka Doncic': 'Luka Dončić',
    'Nikola Vucevic': 'Nikola Vučević',
    'Jonas Valanciunas': 'Jonas Valančiūnas',
    'Dennis Schroder': 'Dennis Schröder',
    'Kristaps Porzingis': 'Kristaps Porziņģis',
    'Bogdan Bogdanovic': 'Bogdan Bogdanović',
    'Dario Saric': 'Dario Šarić',
    'Nikola Jovic': 'Nikola Jović',
    'Vlatko Cancar': 'Vlatko Čančar',
    'Jaren Jackson': 'Jaren Jackson Jr.',
    'Michael Porter Jr': 'Michael Porter Jr.',
    'Jimmy Butler': 'Jimmy Butler III',
    'C.J. McCollum': 'CJ McCollum',
    'Jabari Smith Jr': 'Jabari Smith Jr.',
    'Nicolas Claxton': 'Nic Claxton',
    'Vit Krejci': 'Vít Krejčí',
    'Gary Trent Jr': 'Gary Trent Jr.',
    'Jaime Jaquez Jr': 'Jaime Jaquez Jr.',
    'Isaiah Stewart II': 'Isaiah Stewart',
    'Carlton Carrington': 'Bub Carrington',
    'Tim Hardaway Jr': 'Tim Hardaway Jr.',
    'Jaren Jackson Jr': 'Jaren Jackson Jr.',
    'Vincent Williams Jr': 'Vincent Williams Jr.',
    'Jusuf Nurkic': 'Jusuf Nurkić',
    'Tidjane Salaun': 'Tidjane Salaün', 
    'Moussa Diabate': 'Moussa Diabaté', 
    'Robert Williams': 'Robert Williams III',
}

# Players listed as questionable/may not play
questionablePlayers = {
    "CHA": ["Coby White"],
    "GSW": ["Kristaps Porziņģis", "LJ Cryer"],
    "IND": ["Jarace Walker", "Ben Sheppard"],
    "NOP": ["Yves Missi", "Jordan Hawkins"],
    "SAC": ["DeMar DeRozan"],
    "TOR": ["Sandro Mamukelashvili", "Immanuel Quickley", "Collin Murray-Boyles"],
    "WAS": ["Jaden Hardy", "Tre Johnson"],
}

