projectedStartingFive = {
    "ATL": ["Dyson Daniels", "Onyeka Okongwu", "CJ McCollum", "Jalen Johnson", "Nickeil Alexander-Walker"],
    "BKN": ["Ben Saraf", "Trevon Scott", "Tyson Etienne", "E.J. Liddell", "Malachi Smith"],
    "BOS": ["Jordan Walsh", "Hugo Gonzalez", "Baylor Scheierman", "Luka Garza", "Ron Harper"],
    "CHA": ["Moussa Diabaté", "Miles Bridges", "LaMelo Ball", "Kon Knueppel", "Brandon Miller"],
    "CHI": ["Tre Jones", "Leonard Miller"],
    "CLE": ["Jaylon Tyson", "Nae'Qwan Tomlin", "Larry Nance", "Craig Porter", "Max Strus"],
    "DAL": ["Ryan Nembhard", "Moussa Cisse", "Max Christie", "Khris Middleton", "Cooper Flagg"],
    "DEN": ["Julian Strawther", "Tyus Jones", "Bruce Brown", "David Roddy"],
    "DET": ["Ausar Thompson", "Tobias Harris", "Paul Reed", "Cade Cunningham", "Duncan Robinson"],
    "GSW": ["Brandin Podziemski", "Stephen Curry", "Gui Santos", "Kristaps Porziņģis"],
    "HOU": ["Tari Eason", "Reed Sheppard", "Clint Capela", "Josh Okogie", "Jae'Sean Tate"],
    "IND": ["Micah Potter", "Quenton Jackson", "Ethan Thompson"],
    "LAC": ["Derrick Jones", "Darius Garland", "Kris Dunn", "Brook Lopez"],
    "LAL": ["Marcus Smart", "Jake LaRavia", "Deandre Ayton", "Luke Kennard"],
    "MEM": ["Jahmai Mashack", "Lucas Williamson", "Dariq Whitehead"],
    "MIA": ["Andrew Wiggins", "Bam Adebayo", "Tyler Herro", "Davion Mitchell"],
    "MIL": ["Jericho Sims", "AJ Green", "Taurean Prince", "Cormac Ryan", "Ousmane Dieng"],
    "MIN": ["Joan Beringer", "Julian Phillips", "Donte DiVincenzo", "Jaylen Clark", "Terrence Shannon"],
    "NOP": ["Kevon Looney", "Jeremiah Fears", "Derik Queen", "Jordan Poole", "Micah Peavy"],
    "NYK": ["Mohamed Diawara", "Landry Shamet", "Mikal Bridges", "Miles McBride", "Ariel Hukporti"],
    "OKC": ["Luguentz Dort", "Aaron Wiggins", "Branden Carlson", "Nikola Topic", "Jared McCain"],
    "ORL": ["Wendell Carter", "Paolo Banchero", "Franz Wagner", "Jalen Suggs", "Desmond Bane"],
    "PHI": ["Adem Bona", "Tyrese Maxey", "Paul George", "VJ Edgecombe", "Kelly Oubre"],
    "PHX": ["Ryan Dunn"],
    "POR": ["Jrue Holiday", "Scoot Henderson", "Donovan Clingan", "Deni Avdija", "Toumani Camara"],
    "SAC": ["Maxime Raynaud", "Daeqwon Plowden", "Devin Carter", "Precious Achiuwa", "Nique Clifford"],
    "SAS": ["Julian Champagnie", "De'Aaron Fox"],
    "TOR": ["Scottie Barnes", "Immanuel Quickley", "Jakob Poeltl", "Brandon Ingram"],
    "UTA": ["Cody Williams", "Oscar Tshiebwe", "Ace Bailey", "Bez Mbeng", "Brice Sensabaugh"],
    "WAS": ["Will Riley", "Julian Reese", "Bub Carrington", "Leaky Black"],
}

mainStartingFive = {
    "ATL": ["CJ McCollum", "Nickeil Alexander-Walker", "Dyson Daniels", "Jalen Johnson", "Onyeka Okongwu"],
    "BOS": ["Derrick White", "Jaylen Brown", "Sam Hauser", "Jayson Tatum", "Neemias Queta"],
    "BKN": ["Nolan Traore", "Drake Powell", "Ziaire Williams", "Noah Clowney", "Nic Claxton"],
    "CHA": ["LaMelo Ball", "Kon Knueppel", "Brandon Miller", "Miles Bridges", "Moussa Diabaté"],
    "CHI": ["Josh Giddey", "Tre Jones", "Isaac Okoro", "Matas Buzelis", "Nick Richards"],
    "CLE": ["James Harden", "Donovan Mitchell", "Dean Wade", "Evan Mobley", "Jarrett Allen"],
    "DAL": ["Cooper Flagg", "Max Christie", "Naji Marshall", "P.J. Washington", "Daniel Gafford"],
    "DEN": ["Jamal Murray", "Christian Braun", "Cameron Johnson", "Aaron Gordon", "Nikola Jokić"],
    "DET": ["Cade Cunningham", "Duncan Robinson", "Ausar Thompson", "Tobias Harris", "Jalen Duren"],
    "GSW": ["Stephen Curry", "De'Anthony Melton", "Gui Santos", "Draymond Green", "Kristaps Porziņģis"],
    "HOU": ["Amen Thompson", "Reed Sheppard", "Kevin Durant", "Jabari Smith Jr.", "Alperen Sengun"],
    "IND": ["Andrew Nembhard", "Aaron Nesmith", "Jarace Walker", "Pascal Siakam", "Jay Huff"],
    "LAC": ["Darius Garland", "Kris Dunn", "Kawhi Leonard", "Derrick Jones Jr.", "Brook Lopez"],
    "LAL": ["Luke Kennard", "Marcus Smart", "Jake LaRavia", "LeBron James", "Deandre Ayton"],
    "MEM": ["Javon Small", "Ty Jerome", "Cedric Coward", "GG Jackson", "Olivier-Maxence Prosper"],
    "MIA": ["Davion Mitchell", "Tyler Herro", "Norman Powell", "Andrew Wiggins", "Bam Adebayo"],
    "MIL": ["Ryan Rollins", "AJ Green", "Ousmane Dieng", "Kyle Kuzma", "Myles Turner"],
    "MIN": ["Donte DiVincenzo", "Anthony Edwards", "Jaden McDaniels", "Julius Randle", "Rudy Gobert"],
    "NOP": ["Dejounte Murray", "Trey Murphy III", "Saddiq Bey", "Zion Williamson", "Herbert Jones"],
    "NYK": ["Jalen Brunson", "Josh Hart", "Mikal Bridges", "OG Anunoby", "Karl-Anthony Towns"],
    "OKC": ["Shai Gilgeous-Alexander", "Luguentz Dort", "Jalen Williams", "Chet Holmgren", "Isaiah Hartenstein"],
    "ORL": ["Jalen Suggs", "Desmond Bane", "Franz Wagner", "Paolo Banchero", "Wendell Carter Jr."],
    "PHI": ["Tyrese Maxey", "VJ Edgecombe", "Kelly Oubre Jr.", "Paul George", "Joel Embiid"],
    "PHX": ["Devin Booker", "Jalen Green", "Jordan Goodwin", "Dillon Brooks", "Mark Williams"],
    "POR": ["Jrue Holiday", "Toumani Camara", "Deni Avdija", "Jerami Grant", "Donovan Clingan"],
    "SAC": ["Russell Westbrook", "Nique Clifford", "DeMar DeRozan", "Precious Achiuwa", "Maxime Raynaud"],
    "SAS": ["De'Aaron Fox", "Stephon Castle", "Devin Vassell", "Julian Champagnie", "Victor Wembanyama"],
    "TOR": ["Immanuel Quickley", "Brandon Ingram", "RJ Barrett", "Scottie Barnes", "Jakob Poeltl"],
    "UTA": ["Isaiah Collier", "Cody Williams", "Brice Sensabaugh", "Ace Bailey", "Kyle Filipowski"],
    "WAS": ["Bub Carrington", "Tre Johnson", "Bilal Coulibaly", "Will Riley", "Tristan Vukcevic"],
}

team3StarsPerTeam = {
    "OKC": ["Shai Gilgeous-Alexander", "Chet Holmgren", "Jalen Williams"], 
    "DEN": ['Nikola Jokić', "Jamal Murray", "Aaron Gordon"], 
    "NYK": ['Jalen Brunson', "Karl-Anthony Towns", "OG Anunoby"], 
    "CLE": ["Donovan Mitchell", "James Harden", "Evan Mobley"],
    "ORL": ["Franz Wagner", "Paolo Banchero", "Desmond Bane"], 
    "MIN": ["Anthony Edwards", "Julius Randle", "Rudy Gobert"], 
    "GSW": ["Stephen Curry", "Jimmy Butler", "Kristaps Porziņģis"], 
    "LAL": ["Luka Dončić", "LeBron James", "Austin Reaves"], 
    "HOU": ["Kevin Durant", "Alperen Sengun", "Amen Thompson"],
    "SAS": ["Victor Wembanyama", "Stephon Castle", "De'Aaron Fox"], 
    "LAC": ["Kawhi Leonard", 'Darius Garland', 'Bennedict Mathurin'], 
    "DET": ["Cade Cunningham", "Ausar Thompson", "Jalen Duren"],
    "ATL": ["Jalen Johnson", "Dyson Daniels", "Nickeil Alexander-Walker"],
    "SAC": ["Domantas Sabonis", 'Demar DeRozan', 'Zach LaVine'], 
    "DAL": ["Cooper Flagg", "Kyrie Irving", "Naji Marshall"],
    "MIA": ["Bam Adebayo", "Tyler Herro", "Norman Powell"],
    "TOR": ["Brandon Ingram", "Scottie Barnes", "Immanuel Quickley"],
    "MEM": ["Ty Jerome", "Ja Morant", "Zach Edey"],
    "PHI": ["Tyrese Maxey", "Joel Embiid", "Paul George"],
    "BOS": ["Jaylen Brown", "Jayson Tatum", "Derrick White"],
    "IND": ["Pascal Siakam", "Tyrese Haliburton", "Ivica Zubac"],
    "PHX": ["Devin Booker", "Jalen Green", "Dillon Brooks"],
    "MIL": ["Giannis Antetokounmpo", "Kevin Porter Jr.", "Ryan Rollins"],
    "NOP": ["Zion Williamson", "Dejounte Murray", "Trey Murphy III"],
    "POR": ["Deni Avdija", "Shaedon Sharpe", "Donovan Clingan"],
    "CHI": ["Josh Giddey", "Matas Buzelis", "Tre Jones"],
    "UTA": ["Lauri Markkanen", "Keyonte George", "Jaren Jackson Jr."],
    "CHA": ["LaMelo Ball", "Kon Knueppel", "Brandon Miller"],
    "BKN": ["Michael Porter Jr.", "Nic Claxton", "Egor Demin"],
    "WAS": ["Trae Young", "Anthony Davis", "Alex Sarr"]
}

# Name mapping dictionary to handle special characters in player names
nameDict = {
    'Nikola Jokic': 'Nikola Jokić',
    'Luka Doncic': 'Luka Dončić',
    'Nikola Vucevic': 'Nikola Vučević',
    'Jonas Valanciunas': 'Jonas Valančiūnas',
    'Dennis Schroder': 'Dennis Schröder',
    'Kristaps Porzingis': 'Kristaps Porziņģis',
    'Bogdan Bogdanovic': 'Bogdan Bogdanović',
    'Dario Saric': 'Dario Šarić',
    'Nikola Jovic': 'Nikola Jović',
    'Vlatko Cancar': 'Vlatko Čančar',
    'Jaren Jackson': 'Jaren Jackson Jr.',
    'Michael Porter Jr': 'Michael Porter Jr.',
    'Jimmy Butler': 'Jimmy Butler III',
    'C.J. McCollum': 'CJ McCollum',
    'Jabari Smith Jr': 'Jabari Smith Jr.',
    'Nicolas Claxton': 'Nic Claxton',
    'Vit Krejci': 'Vít Krejčí',
    'Gary Trent Jr': 'Gary Trent Jr.',
    'Jaime Jaquez Jr': 'Jaime Jaquez Jr.',
    'Isaiah Stewart II': 'Isaiah Stewart',
    'Carlton Carrington': 'Bub Carrington',
    'Tim Hardaway Jr': 'Tim Hardaway Jr.',
    'Jaren Jackson Jr': 'Jaren Jackson Jr.',
    'Vincent Williams Jr': 'Vincent Williams Jr.',
    'Jusuf Nurkic': 'Jusuf Nurkić',
    'Tidjane Salaun': 'Tidjane Salaün', 
    'Moussa Diabate': 'Moussa Diabaté', 
    'Robert Williams': 'Robert Williams III',
}

# Players listed as questionable/may not play
questionablePlayers = {
    "ATL": ["Jalen Johnson", "CJ McCollum", "Nickeil Alexander-Walker", "Onyeka Okongwu", "Dyson Daniels", "Jonathan Kuminga"],
    "BKN": ["Nolan Traore"],
    "DEN": ["Nikola Jokić"],
    "GSW": ["Draymond Green", "Will Richard"],
    "IND": ["Ben Sheppard", "Jarace Walker", "Kobe Brown"],
    "LAC": ["Kawhi Leonard"],
    "LAL": ["Jaxson Hayes", "LeBron James"],
    "MEM": ["Olivier-Maxence Prosper", "Walter Clayton", "Adama Bal"],
    "MIA": ["Norman Powell"],
    "MIL": ["Gary Harris", "Pete Nance"],
    "ORL": ["Jett Howard", "Jonathan Isaac"],
    "PHX": ["Jordan Goodwin", "Mark Williams", "Haywood Highsmith", "Jalen Green", "Collin Gillespie"],
    "POR": ["Vít Krejčí"],
    "SAS": ["Victor Wembanyama", "Stephon Castle", "Devin Vassell"],
    "TOR": ["Collin Murray-Boyles", "RJ Barrett", "Trayce Jackson-Davis"],
    "WAS": ["Anthony Gill"],
}

