projectedStartingFive = {
    "ATL": ["Zaccharie Risacher", "Jalen Johnson", "Dyson Daniels", "Onyeka Okongwu", "Trae Young"],
    "BKN": ["Terance Mann", "Nic Claxton", "Noah Clowney", "Egor Demin", "Michael Porter"],
    "BOS": ["Derrick White", "Payton Pritchard", "Jordan Walsh", "Jaylen Brown", "Neemias Queta"],
    "CHA": ["Kon Knueppel", "Brandon Miller", "Ryan Kalkbrenner", "Sion James", "Miles Bridges"],
    "CHI": ["Josh Giddey", "Coby White", "Matas Buzelis", "Nikola Vučević", "Isaac Okoro"],
    "CLE": ["Jaylon Tyson", "Darius Garland", "Jarrett Allen", "Dean Wade"],
    "DAL": ["Cooper Flagg", "Naji Marshall", "Daniel Gafford", "Ryan Nembhard", "P.J. Washington"],
    "DEN": ["Spencer Jones", "Nikola Jokić", "Cameron Johnson", "Jamal Murray"],
    "DET": ["Cade Cunningham", "Duncan Robinson", "Ausar Thompson", "Jalen Duren", "Tobias Harris"],
    "GSW": ["Draymond Green", "Quinten Post", "Jimmy Butler III", "Stephen Curry", "Moses Moody"],
    "HOU": ["Kevin Durant", "Alperen Sengun", "Jabari Smith", "Amen Thompson", "Josh Okogie"],
    "IND": ["Jay Huff", "Andrew Nembhard", "Pascal Siakam", "Bennedict Mathurin", "Ethan Thompson"],
    "LAC": ["Kawhi Leonard", "James Harden", "Kris Dunn", "John Collins", "Ivica Zubac"],
    "LAL": ["Marcus Smart", "Deandre Ayton", "LeBron James", "Rui Hachimura", "Luka Dončić"],
    "MEM": ["Cedric Coward", "Vince Williams", "Jaylen Wells", "Santi Aldama", "Jaren Jackson Jr."],
    "MIA": ["Davion Mitchell", "Andrew Wiggins", "Bam Adebayo"],
    "MIL": ["Ryan Rollins", "Gary Trent", "Kevin Porter", "Myles Turner", "Kyle Kuzma"],
    "MIN": ["Julius Randle", "Jaden McDaniels", "Donte DiVincenzo", "Rudy Gobert"],
    "NOP": ["Derik Queen", "Trey Murphy", "Jeremiah Fears", "Saddiq Bey", "Herbert Jones"],
    "NYK": ["Mikal Bridges", "Jalen Brunson", "OG Anunoby"],
    "OKC": ["Chet Holmgren", "Jalen Williams", "Luguentz Dort", "Shai Gilgeous-Alexander"],
    "ORL": ["Paolo Banchero", "Anthony Black", "Jalen Suggs", "Wendell Carter", "Desmond Bane"],
    "PHI": ["VJ Edgecombe", "Paul George", "Dominick Barlow", "Tyrese Maxey"],
    "PHX": ["Dillon Brooks", "Devin Booker", "Grayson Allen", "Mark Williams", "Collin Gillespie"],
    "POR": ["Jerami Grant", "Toumani Camara", "Donovan Clingan", "Deni Avdija", "Shaedon Sharpe"],
    "SAC": ["DeMar DeRozan", "Keegan Murray", "Russell Westbrook", "Maxime Raynaud"],
    "SAS": ["Harrison Barnes", "De'Aaron Fox", "Stephon Castle", "Devin Vassell", "Luke Kornet"],
    "TOR": ["Brandon Ingram", "Immanuel Quickley", "Ochai Agbaji", "Scottie Barnes", "Jakob Poeltl"],
    "UTA": ["Keyonte George", "Lauri Markkanen", "Kyle Filipowski", "Brice Sensabaugh", "Ace Bailey"],
    "WAS": ["Justin Champagnie", "Kyshawn George", "Marvin Bagley", "Bub Carrington", "CJ McCollum"],
}

mainStartingFive = {
    "ATL": ["Nickeil Alexander-Walker", "Dyson Daniels", "Zaccharie Risacher", "Jalen Johnson", "Kristaps Porziņģis"],
    "BOS": ["Derrick White", "Payton Pritchard", "Jaylen Brown", "Jordan Walsh", "Neemias Queta"],
    "BKN": ["Egor Demin", "Noah Clowney", "Terance Mann", "Michael Porter Jr.", "Nic Claxton"],
    "CHA": ["LaMelo Ball", "Kon Knueppel", "Brandon Miller", "Miles Bridges", "Ryan Kalkbrenner"],
    "CHI": ["Josh Giddey", "Coby White", "Isaac Okoro", "Matas Buzelis", "Nikola Vučević"],
    "CLE": ["Darius Garland", "Donovan Mitchell", "De'Andre Hunter", "Evan Mobley", "Jarrett Allen"],
    "DAL": ["Brondon Williams", "Max Christie", "P.J. Washington", "Cooper Flagg", "Daniel Gafford"],
    "DEN": ["Jamal Murray", "Peyton Watson", "Cameron Johnson", "Aaron Gordon", "Nikola Jokić"],
    "DET": ["Cade Cunningham", "Duncan Robinson", "Ausar Thompson", "Tobias Harris", "Jalen Duren"],
    "GSW": ["Stephen Curry", "Jimmy Butler III", "Will Richard", "Draymond Green", "Moses Moody"],
    "HOU": ["Amen Thompson", "Josh Okogie", "Kevin Durant", "Jabari Smith Jr.", "Alperen Sengun"],
    "IND": ["Andrew Nembhard", "Bennedict Mathurin", "Ben Sheppard", "Pascal Siakam", "Isaiah Jackson"],
    "LAC": ["James Harden", "Kriss Dunn", "Kawhi Leonard", "John Collins", "Ivica Zubac"],
    "LAL": ["Luka Dončić", "Austin Reaves", "LeBron James", "Rui Hachimura", "Deandre Ayton"],
    "MEM": ["Ja Morant", "Cedric Coward", "Jaylen Wells", "Jaren Jackson Jr.", "Zach Edey"],
    "MIA": ["Davion Mitchell", "Norman Powell", "Pelle Larsson", "Andrew Wiggins", "Bam Adebayo"],
    "MIL": ["Ryan Rollins", "AJ Green", "Kyle Kuzma", "Giannis Antetokounmpo", "Myles Turner"],
    "MIN": ["Donte DiVincenzo", "Anthony Edwards", "Jaden McDaniels", "Julius Randle", "Rudy Gobert"],
    "NOP": ["Jeremiah Fears", "Trey Murphy III", "Herbert Jones", "Zion Williamson", "Derik Queen"],
    "NYK": ["Jalen Brunson", "Mikal Bridges", "OG Anunoby", "Karl-Anthony Towns", "Mitchell Robinson"],
    "OKC": ["Shai Gilgeous-Alexander", "Cason Wallace", "Luguentz Dort", "Chet Holmgren", "Isaiah Hartenstein"],
    "ORL": ["Jalen Suggs", "Desmond Bane", "Franz Wagner", "Paolo Banchero", "Wendell Carter Jr."],
    "PHI": ["Tyrese Maxey", "VJ Edgecombe", "Kelly Oubre Jr.", "Paul George", "Joel Embiid"],
    "PHX": ["Devin Booker", "Grayson Allen", "Dillon Brooks", "Royce O'Neale", "Mark Williams"],
    "POR": ["Jrue Holiday", "Shaedon Sharpe", "Toumani Camara", "Deni Avdija", "Donovan Clingan"],
    "SAC": ["Russell Westbrook", "Zach LaVine", "DeMar DeRozan", "Keegan Murray", "Domantas Sabonis"],
    "SAS": ["De'Aaron Fox", "Stephon Castle", "Devin Vassell", "Harrison Barnes", "Victor Wembanyama"],
    "TOR": ["Immanuel Quickley", "Brandon Ingram", "RJ Barrett", "Scottie Barnes", "Jakob Poeltl"],
    "UTA": ["Keyonte George", "Svi Mykhailiuk", "Ace Bailey", "Lauri Markkanen", "Jusuf Nurkic"],
    "WAS": ["CJ McCollum", "Kyshawn George", "Bilal Coulibaly", "Khris Middleton", "Alex Sarr"]
}

teamStarPlayer = {
    "OKC": "Shai Gilgeous-Alexander", 
    "DEN": 'Nikola Jokić', 
    "NYK": 'Jalen Brunson', 
    "CLE": "Donovan Mitchell",
    "ORL": "Paolo Banchero", 
    "MIN": "Julius Randle", 
    "GSW": "Stephen Curry", 
    "LAL": 'Luka Dončić', 
    "HOU": "Alperen Sengun",
    "SAS": "Victor Wembanyama", 
    "LAC": "James Harden", 
    "DET": "Cade Cunningham",
    "ATL": "Jalen Johnson",
    "SAC": "Zach LaVine", 
    "DAL": "D'Angelo Russell",
    "MIA": "Norman Powell",
    "TOR": "Brandon Ingram",
    "MEM": "Cedric Coward",
    "PHI": "Tyrese Maxey",
    "BOS": "Jaylen Brown",
    "IND": "Pascal Siakam",
    "PHX": "Devin Booker",
    "MIL": "Giannis Antetokounmpo",
    "NOP": "Trey Murphy III",
    "POR": "Deni Avdija",
    "CHI": "Ayo Dosunmu",
    "UTA": "Lauri Markkanen",
    "CHA": "LaMelo Ball",
    "BKN": "Michael Porter Jr.",
    "WAS": "Alex Sarr"
}

# Name mapping dictionary to handle special characters in player names
nameDict = {
    'Nikola Jokic': 'Nikola Jokić',
    'Luka Doncic': 'Luka Dončić',
    'Nikola Vucevic': 'Nikola Vučević',
    'Jonas Valanciunas': 'Jonas Valančiūnas',
    'Dennis Schroder': 'Dennis Schröder',
    'Kristaps Porzingis': 'Kristaps Porziņģis',
    'Bogdan Bogdanovic': 'Bogdan Bogdanović',
    'Dario Saric': 'Dario Šarić',
    'Nikola Jovic': 'Nikola Jović',
    'Vlatko Cancar': 'Vlatko Čančar',
    'Jaren Jackson': 'Jaren Jackson Jr.',
    'Michael Porter Jr': 'Michael Porter Jr.',
    'Jimmy Butler': 'Jimmy Butler III',
    'C.J. McCollum': 'CJ McCollum',
    'Jabari Smith Jr': 'Jabari Smith Jr.',
    'Nicolas Claxton': 'Nic Claxton',
    'Vit Krejci': 'Vít Krejčí',
    'Gary Trent Jr': 'Gary Trent Jr.',
    'Jaime Jaquez Jr': 'Jaime Jaquez Jr.',
    'Isaiah Stewart II': 'Isaiah Stewart',
    'Carlton Carrington': 'Bub Carrington',
    'Tim Hardaway Jr': 'Tim Hardaway Jr.',
    'Jaren Jackson Jr': 'Jaren Jackson Jr.',
    'Vincent Williams Jr': 'Vincent Williams Jr.',
    'Jusuf Nurkic': 'Jusuf Nurkić',
    'Tidjane Salaun': 'Tidjane Salaün', 
    'Moussa Diabate': 'Moussa Diabaté', 
    'Robert Williams': 'Robert Williams III',
}

# Players listed as questionable/may not play
questionablePlayers = {
    "ATL": ["N'Faly Dante"],
    "CHI": ["Tre Jones", "Ayo Dosunmu"],
    "CLE": ["Donovan Mitchell"],
    "MIA": ["Tyler Herro"],
    "MIN": ["Anthony Edwards"],
    "NYK": ["Karl-Anthony Towns", "Mitchell Robinson", "Josh Hart", "Miles McBride"],
    "OKC": ["Jaylin Williams", "Isaiah Hartenstein"],
    "PHI": ["Joel Embiid"],
}

