projectedStartingFive = {
    "ATL": ["Trae Young", "Dyson Daniels", "Zaccharie Risacher", "Jalen Johnson", "Kristaps Porziņģis"],
    "BOS": ["Derrick White", "Payton Pritchard", "Jaylen Brown", "Hugo Gonzalez", "Neemias Queta"],
    "BKN": ["Ben Saraf", "Cam Thomas", "Terrence Mann", "Michael Porter Jr.", "Nicolas Claxton"],
    "CHA": ["LaMelo Ball", "Collin Sexton", "Kon Knueppel", "Miles Bridges", "Ryan Kalkbrenner"],
    "CHI": ["Josh Giddey", "Coby White", "Isaac Okoro", "Matas Buzelis", "Nikola Vučević"],
    "CLE": ["Donovan Mitchell", "Sam Merrill", "De'Andre Hunter", "Evan Mobley", "Jarrett Allen"],
    "DAL": ["P.J. Washington", "Klay Thompson", "Cooper Flagg", "Anthony Davis", "Dereck Lively II"],
    "DEN": ["Jamal Murray", "Christian Braun", "Cameron Johnson", "Aaron Gordon", "Nikola Jokić"],
    "DET": ["Cade Cunningham", "Duncan Robinson", "Ausar Thompson", "Tobias Harris", "Jalen Duren"],
    "GSW": ["Stephen Curry", "Moses Moody", "Jalen Butler III", "Draymond Green", "Al Horford"],
    "HOU": ["Reed Sheppard", "Amen Thompson", "Kevin Durant", "Jabari Smith Jr.", "Alperen Şengün"],
    "IND": ["Ben Sheppard", "RayJ Dennis", "Aaron Nesmith", "Pascal Siakam", "James Wiseman"],
    "LAC": ["James Harden", "Bradley Beal", "Kawhi Leonard", "John Collins", "Ivica Zubac"],
    "LAL": ["Luka Dončić", "Austin Reaves", "Rui Hachimura", "Jared Vanderbilt", "Deandre Ayton"],
    "MEM": ["Ja Morant", "Kentavious Caldwell-Pope", "Jaylen Wells", "Jaren Jackson Jr.", "Zach Edey"],
    "MIA": ["Donovan Mitchell", "Norman Powell", "Andrew Wiggins", "Bam Adebayo", "Kel'el Ware"],
    "MIL": ["Ryan Rollins", "Gary Trent Jr.", "AJ Green", "Giannis Antetokounmpo", "Myles Turner"],
    "MIN": ["Donte DiVincenzo", "Anthony Edwards", "Jaden McDaniels", "Julius Randle", "Rudy Gobert"],
    "NOP": ["Jordan Poole", "Trey Murphy III", "Herb Jones", "Zion Williamson", "Yves Missi"],
    "NYK": ["Jalen Brunson", "Miles McBride", "Mikal Bridges", "OG Anunoby", "Karl-Anthony Towns"],
    "OKC": ["Shai Gilgeous-Alexander", "Luguentz Dort", "Jalen Williams", "Chet Holmgren", "Isaiah Hartenstein"],
    "ORL": ["Jalen Suggs", "Desmond Bane", "Franz Wagner", "Paolo Banchero", "Wendell Carter Jr."],
    "PHI": ["Tyrese Maxey", "VJ Edgecombe", "Kelly Oubre Jr.", "Paul George", "Joel Embiid"],
    "PHX": ["Devin Booker", "Jalen Green", "Ryan Dunn", "Dillon Brooks", "Mark Williams"],
    "POR": ["Jrue Holiday", "Shaedon Sharpe", "Deni Avdija", "Toumani Camara", "Donovan Clingan"],
    "SAC": ["Dennis Schröder", "Keon Ellis", "Zach LaVine", "DeMar DeRozan", "Domantas Sabonis"],
    "SAS": ["Stephon Castle", "Devin Vassell","Julian Champagnie", "Harrison Barnes", "Victor Wembanyama"],
    "TOR": ["Immanuel Quickley", "RJ Barrett", "Brandon Ingram", "Scottie Barnes", "Jakob Poeltl"],
    "UTA": ["Isaiah Collier", "Ace Bailey", "Taylor Hendricks", "Lauri Markkanen", "Walker Kessler"],
    "WAS": ["Bub Carrington", "CJ McCollum", "Khris Middleton", "Kyshawn George", "Alex Sarr"]
}

mainStartingFive = {
    "ATL": ["Trae Young", "Dyson Daniels", "Zaccharie Risacher", "Jalen Johnson", "Kristaps Porziņģis"],
    "BOS": ["Derrick White", "Anfernee Simons", "Jaylen Brown", "Jayson Tatum", "Neemias Queta"],
    "BKN": ["Egor Demin", "Cam Thomas", "Terrence Mann", "Michael Porter Jr.", "Nicolas Claxton"],
    "CHA": ["LaMelo Ball", "Brandon Miller", "Kon Knueppel", "Miles Bridges", "Moussa Diabate"],
    "CHI": ["Josh Giddey", "Coby White", "Isaac Okoro", "Matas Buzelis", "Nikola Vučević"],
    "CLE": ["Darius Garland", "Donovan Mitchell", "De'Andre Hunter", "Evan Mobley", "Jarrett Allen"],
    "DAL": ["D'Angelo Russell", "Klay Thompson", "Cooper Flagg", "Anthony Davis", "Dereck Lively II"],
    "DEN": ["Jamal Murray", "Christian Braun", "Cameron Johnson", "Aaron Gordon", "Nikola Jokić"],
    "DET": ["Cade Cunningham", "Caris LeVert", "Ausar Thompson", "Tobias Harris", "Jalen Duren"],
    "GSW": ["Stephen Curry", "Moses Moody", "Jalen Butler III", "Draymond Green", "Al Horford"],
    "HOU": ["Fred VanVleet", "Amen Thompson", "Kevin Durant", "Jabari Smith Jr.", "Alperen Şengün"],
    "IND": ["Tyrese Haliburton", "Andrew Nembhard", "Bennedict Mathurin", "Pascal Siakam", "Isaiah Jackson"],
    "LAC": ["James Harden", "Bradley Beal", "Kawhi Leonard", "John Collins", "Ivica Zubac"],
    "LAL": ["Luka Dončić", "Austin Reaves", "Rui Hachimura", "LeBron James", "Deandre Ayton"],
    "MEM": ["Ja Morant", "Kentavious Caldwell-Pope", "Jaylen Wells", "Jaren Jackson Jr.", "Zach Edey"],
    "MIA": ["Donovan Mitchell", "Norman Powell", "Andrew Wiggins", "Bam Adebayo", "Kel'el Ware"],
    "MIL": ["Kevin Porter Jr.", "Gary Trent Jr.", "Kyle Kuzma", "Giannis Antetokounmpo", "Myles Turner"],
    "MIN": ["Mike Conley", "Anthony Edwards", "Jaden McDaniels", "Julius Randle", "Rudy Gobert"],
    "NOP": ["Jordan Poole", "Trey Murphy III", "Herb Jones", "Zion Williamson", "Yves Missi"],
    "NYK": ["Jalen Brunson", "Mikal Bridges", "OG Anunoby", "Karl-Anthony Towns", "Mitchell Robinson"],
    "OKC": ["Shai Gilgeous-Alexander", "Luguentz Dort", "Jalen Williams", "Chet Holmgren", "Isaiah Hartenstein"],
    "ORL": ["Jalen Suggs", "Desmond Bane", "Franz Wagner", "Paolo Banchero", "Wendell Carter Jr."],
    "PHI": ["Tyrese Maxey", "VJ Edgecombe", "Kelly Oubre Jr.", "Paul George", "Joel Embiid"],
    "PHX": ["Devin Booker", "Jalen Green", "Ryan Dunn", "Dillon Brooks", "Mark Williams"],
    "POR": ["Jrue Holiday", "Shaedon Sharpe", "Deni Avdija", "Toumani Camara", "Donovan Clingan"],
    "SAC": ["Dennis Schröder", "Keon Ellis", "Zach LaVine", "DeMar DeRozan", "Domantas Sabonis"],
    "SAS": ["De'Aaron Fox", "Stephon Castle", "Devin Vassell", "Harrison Barnes", "Victor Wembanyama"],
    "TOR": ["Immanuel Quickley", "RJ Barrett", "Brandon Ingram", "Scottie Barnes", "Jakob Poeltl"],
    "UTA": ["Isaiah Collier", "Ace Bailey", "Taylor Hendricks", "Lauri Markkanen", "Walker Kessler"],
    "WAS": ["Bub Carrington", "CJ McCollum", "Khris Middleton", "Bilal Coulibaly", "Alex Sarr"]
}

teamStarPlayer = {
    "OKC": "Shai Gilgeous-Alexander", 
    "DEN": 'Nikola Jokić', 
    "NYK": 'Jalen Brunson', 
    "CLE": "Donovan Mitchell",
    "ORL": "Paolo Banchero", 
    "MIN": "Anthony Edwards", 
    "GSW": "Stephen Curry", 
    "LAL": 'Luka Dončić', 
    "HOU": "Kevin Durant",
    "SAS": "Victor Wembanyama", 
    "LAC": "Kawhi Leonard", 
    "DET": "Cade Cunningham",
    "ATL": "Trae Young",
    "SAC": "Zach LaVine", 
    "DAL": "Anthony Davis",
    "MIA": "Tyler Herro",
    "TOR": "Scottie Barnes",
    "MEM": "Ja Morant",
    "PHI": "Joel Embiid",
    "BOS": "Jaylen Brown",
    "IND": "Pascal Siakam",
    "PHX": "Devin Booker",
    "MIL": "Giannis Antetokounmpo",
    "NOP": "Zion Williamson",
    "POR": "Deni Avdija",
    "CHI": "Coby White",
    "UTA": "Lauri Markkanen",
    "CHA": "LaMelo Ball",
    "BKN": "Cam Thomas",
    "WAS": "CJ McCollum"
}