projectedStartingFive = {
    "ATL": ["Dyson Daniels", "Zaccharie Risacher", "Jalen Johnson", "Nickeil Alexander-Walker", "Kristaps Porzingis"],
    "BKN": ["Noah Clowney", "Cam Thomas", "Terance Mann", "Nic Claxton", "Tyrese Martin"],
    "BOS": ["Payton Pritchard", "Josh Minott", "Jaylen Brown", "Neemias Queta", "Derrick White"],
    "CHA": ["Kon Knueppel", "Collin Sexton", "Miles Bridges", "Sion James", "Ryan Kalkbrenner"],
    "CHI": ["Tre Jones", "Isaac Okoro", "Nikola Vucevic", "Matas Buzelis", "Josh Giddey"],
    "CLE": ["De'Andre Hunter", "Donovan Mitchell", "Evan Mobley", "Jaylon Tyson", "Larry Nance"],
    "DAL": ["P.J. Washington", "Klay Thompson", "Cooper Flagg", "Max Christie", "Daniel Gafford"],
    "DEN": ["Nikola Jokic", "Aaron Gordon", "Christian Braun", "Cameron Johnson", "Jamal Murray"],
    "DET": ["Cade Cunningham", "Jalen Duren", "Duncan Robinson", "Ausar Thompson"],
    "GSW": ["Brandin Podziemski", "Draymond Green", "Stephen Curry", "Jonathan Kuminga", "Jimmy Butler"],
    "HOU": ["Alperen Sengun", "Kevin Durant", "Amen Thompson", "Josh Okogie", "Tari Eason"],
    "IND": ["Jarace Walker", "Aaron Nesmith", "Tyrese Haliburton", "Isaiah Jackson", "Quenton Jackson"],
    "LAC": ["Bradley Beal", "Kawhi Leonard", "James Harden", "Derrick Jones", "Ivica Zubac"],
    "LAL": ["Jake LaRavia", "Rui Hachimura", "Jarred Vanderbilt", "Marcus Smart"],
    "MEM": ["Jock Landale", "Jaylen Wells", "Ja Morant", "Kentavious Caldwell-Pope", "Jaren Jackson"],
    "MIA": ["Kel'el Ware", "Davion Mitchell", "Bam Adebayo", "Andrew Wiggins"],
    "MIL": ["Giannis Antetokounmpo", "Myles Turner", "Gary Trent", "AJ Green", "Ryan Rollins"],
    "MIN": ["Rudy Gobert", "Julius Randle", "Mike Conley", "Jaden McDaniels", "Donte DiVincenzo"],
    "NOP": ["Herbert Jones", "Yves Missi", "Trey Murphy", "Jeremiah Fears", "Zion Williamson"],
    "NYK": ["Jalen Brunson", "Mikal Bridges", "Landry Shamet", "OG Anunoby", "Karl-Anthony Towns"],
    "OKC": ["Aaron Wiggins", "Jaylin Williams", "Ousmane Dieng", "Isaiah Hartenstein", "Shai Gilgeous-Alexander"],
    "ORL": ["Wendell Carter", "Desmond Bane", "Franz Wagner", "Paolo Banchero", "Jalen Suggs"],
    "PHI": ["Adem Bona", "VJ Edgecombe", "Kelly Oubre", "Tyrese Maxey", "Jabari Walker"],
    "PHX": ["Royce O'Neale", "Grayson Allen", "Mark Williams", "Devin Booker", "Ryan Dunn"],
    "POR": ["Shaedon Sharpe", "Damian Lillard", "Donovan Clingan", "Toumani Camara", "Jrue Holiday"],
    "SAC": ["Dennis Schroder", "Russell Westbrook", "Domantas Sabonis", "Zach LaVine", "DeMar DeRozan"],
    "SAS": ["Stephon Castle", "Dylan Harper", "Julian Champagnie", "Harrison Barnes", "Victor Wembanyama"],
    "TOR": ["Scottie Barnes", "RJ Barrett", "Immanuel Quickley", "Brandon Ingram", "Collin Murray-Boyles"],
    "UTA": ["Lauri Markkanen", "Svi Mykhailiuk", "Keyonte George", "Jusuf Nurkic", "Taylor Hendricks"],
    "WAS": ["Kyshawn George", "Bilal Coulibaly", "Justin Champagnie", "Alex Sarr", "CJ McCollum"],
}

mainStartingFive = {
    "ATL": ["Nickeil Alexander-Walker", "Dyson Daniels", "Zaccharie Risacher", "Jalen Johnson", "Kristaps Porzingis"],
    "BOS": ["Derrick White", "Payton Pritchard", "Jaylen Brown", "Josh Minott", "Neemias Queta"],
    "BKN": ["Tyrese Martin", "Cam Thomas", "Terance Mann", "Michael Porter Jr.", "Nic Claxton"],
    "CHA": ["LaMelo Ball", "Collin Sexton", "Brandon Miller", "Miles Bridges", "Ryan Kalkbrenner"],
    "CHI": ["Josh Giddey", "Coby White", "Isaac Okoro", "Matas Buzelis", "Nikola Vucevic"],
    "CLE": ["Darius Garland", "Donovan Mitchell", "De'Andre Hunter", "Evan Mobley", "Jarrett Allen"],
    "DAL": ["Cooper Flagg", "Klay Thompson", "P.J. Washington", "Anthony Davis", "Dereck Lively II"],
    "DEN": ["Jamal Murray", "Christian Braun", "Cameron Johnson", "Aaron Gordon", "Nikola Jokic"],
    "DET": ["Cade Cunningham", "Duncan Robinson", "Ausar Thompson", "Tobias Harris", "Jalen Duren"],
    "GSW": ["Stephen Curry", "Jimmy Butler III", "Jonathan Kuminga", "Draymond Green", "Quinten Post"],
    "HOU": ["Amen Thompson", "Josh Okogie", "Kevin Durant", "Jabari Smith Jr.", "Alperen Sengun"],
    "IND": ["Andrew Nembhard", "Bennedict Mathurin", "Aaron Nesmith", "Pascal Siakam", "Isaiah Jackson"],
    "LAC": ["James Harden", "Bradley Beal", "Kawhi Leonard", "Derrick Jones Jr.", "Ivica Zubac"],
    "LAL": ["Luka Doncic", "Austin Reaves", "Marcus Smart", "Rui Hachimura", "Deandre Ayton"],
    "MEM": ["Ja Morant", "Kentavious Caldwell-Pope", "Jaylen Wells", "Jaren Jackson Jr.", "Jock Landale"],
    "MIA": ["Davion Mitchell", "Norman Powell", "Andrew Wiggins", "Bam Adebayo", "Kel'el Ware"],
    "MIL": ["Ryan Rollins", "AJ Green", "Gary Trent Jr.", "Giannis Antetokounmpo", "Myles Turner"],
    "MIN": ["Donte DiVincenzo", "Anthony Edwards", "Jaden McDaniels", "Julius Randle", "Rudy Gobert"],
    "NOP": ["Jeremiah Fears", "Trey Murphy III", "Herbert Jones", "Zion Williamson", "Yves Missi"],
    "NYK": ["Jalen Brunson", "Mikal Bridges", "OG Anunoby", "Karl-Anthony Towns", "Mitchell Robinson"],
    "OKC": ["Shai Gilgeous-Alexander", "Luguentz Dort", "Jaylin Williams", "Chet Holmgren", "Isaiah Hartenstein"],
    "ORL": ["Jalen Suggs", "Desmond Bane", "Franz Wagner", "Paolo Banchero", "Wendell Carter Jr."],
    "PHI": ["Tyrese Maxey", "VJ Edgecombe", "Kelly Oubre Jr.", "Paul George", "Joel Embiid"],
    "PHX": ["Devin Booker", "Jalen Green", "Dillon Brooks", "Ryan Dunn", "Mark Williams"],
    "POR": ["Jrue Holiday", "Shaedon Sharpe", "Toumani Camara", "Deni Avdija", "Donovan Clingan"],
    "SAC": ["Dennis Schroder", "Zach LaVine", "DeMar DeRozan", "Domantas Sabonis", "Dylan Cardwell"],
    "SAS": ["De'Aaron Fox", "Stephon Castle", "Devin Vassell", "Harrison Barnes", "Victor Wembanyama"],
    "TOR": ["Immanuel Quickley", "RJ Barrett", "Brandon Ingram", "Scottie Barnes", "Jakob Poeltl"],
    "UTA": ["Isaiah Collier", "Svi Mykhailiuk", "Lauri Markkanen", "Kyle Filipowski", "Walker Kessler"],
    "WAS": ["CJ McCollum", "Kyshawn George", "Khris Middleton", "Bilal Coulibaly", "Alex Sarr"]
}

teamStarPlayer = {
    "OKC": "Shai Gilgeous-Alexander", 
    "DEN": 'Nikola Jokic', 
    "NYK": 'Jalen Brunson', 
    "CLE": "Donovan Mitchell",
    "ORL": "Paolo Banchero", 
    "MIN": "Anthony Edwards", 
    "GSW": "Stephen Curry", 
    "LAL": 'Luka Doncic', 
    "HOU": "Kevin Durant",
    "SAS": "Victor Wembanyama", 
    "LAC": "Kawhi Leonard", 
    "DET": "Cade Cunningham",
    "ATL": "Trae Young",
    "SAC": "Zach LaVine", 
    "DAL": "Anthony Davis",
    "MIA": "Bam Adebayo",
    "TOR": "Scottie Barnes",
    "MEM": "Ja Morant",
    "PHI": "Tyrese Maxey",
    "BOS": "Jaylen Brown",
    "IND": "Pascal Siakam",
    "PHX": "Devin Booker",
    "MIL": "Giannis Antetokounmpo",
    "NOP": "Zion Williamson",
    "POR": "Deni Avdija",
    "CHI": "Josh Giddey",
    "UTA": "Lauri Markkanen",
    "CHA": "LaMelo Ball",
    "BKN": "Cam Thomas",
    "WAS": "Keyshawn George"
}