projectedStartingFive = {
    "ATL": ["Kristaps Porzingis", "Zaccharie Risacher", "Nickeil Alexander-Walker", "Dyson Daniels", "Jalen Johnson"],
    "BKN": ["Ben Saraf", "Cam Thomas", "Terrence Mann", "Michael Porter Jr.", "Nicolas Claxton"],
    "BOS": ["Neemias Queta", "Jaylen Brown", "Josh Minott", "Payton Pritchard", "Derrick White"],
    "CHA": ["LaMelo Ball", "Miles Bridges", "Kon Knueppel", "Ryan Kalkbrenner", "Sion James"],
    "CHI": ["Isaac Okoro", "Tre Jones", "Nikola Vucevic", "Josh Giddey", "Matas Buzelis"],
    "CLE": ["Lonzo Ball", "Dean Wade", "Jaylon Tyson", "Evan Mobley", "De'Andre Hunter"],
    "DAL": ["Klay Thompson", "Daniel Gafford", "Cooper Flagg", "P.J. Washington", "Max Christie"],
    "DEN": ["Jamal Murray", "Aaron Gordon", "Nikola Jokic", "Christian Braun", "Cameron Johnson"],
    "DET": ["Tobias Harris", "Duncan Robinson", "Cade Cunningham", "Jalen Duren", "Ausar Thompson"],
    "GSW": ["Draymond Green", "Jimmy Butler", "Stephen Curry", "Jonathan Kuminga", "Quinten Post"],
    "HOU": ["Alperen Sengun", "Kevin Durant", "Amen Thompson", "Josh Okogie", "Jabari Smith"],
    "IND": ["Tyrese Haliburton", "Ben Sheppard", "Johnny Furphy", "Taelon Peter", "Pascal Siakam"],
    "LAC": ["Ivica Zubac", "Kawhi Leonard", "Bradley Beal", "James Harden", "Derrick Jones"],
    "LAL": ["Luka Doncic", "Deandre Ayton", "Austin Reaves", "Marcus Smart", "Rui Hachimura"],
    "MEM": ["Jaren Jackson", "Ja Morant", "Jock Landale", "Kentavious Caldwell-Pope", "Jaylen Wells"],
    "MIA": ["Donovan Mitchell", "Pelle Larsson", "Andrew Wiggins", "Bam Adebayo", "Kel'el Ware"],
    "MIL": ["AJ Green", "Giannis Antetokounmpo", "Ryan Rollins", "Myles Turner", "Gary Trent"],
    "MIN": ["Rudy Gobert", "Mike Conley", "Donte DiVincenzo", "Jaden McDaniels", "Julius Randle"],
    "NOP": ["Herbert Jones", "Yves Missi", "Jeremiah Fears", "Zion Williamson", "Trey Murphy"],
    "NYK": ["Karl-Anthony Towns", "Mikal Bridges", "OG Anunoby", "Mitchell Robinson", "Jalen Brunson"],
    "OKC": ["Shai Gilgeous-Alexander", "Cason Wallace", "Luguentz Dort", "Aaron Wiggins", "Isaiah Hartenstein"],
    "ORL": ["Paolo Banchero", "Franz Wagner", "Desmond Bane", "Wendell Carter", "Jalen Suggs"],
    "PHI": ["Paul George", "Tyrese Maxey", "Joel Embiid", "Jabari Walker", "Kelly Oubre"],
    "PHX": ["Devin Booker", "Isaiah Livers", "Ryan Dunn", "Royce O'Neale", "Grayson Allen"],
    "POR": ["Jrue Holiday", "Shaedon Sharpe", "Toumani Camara", "Donovan Clingan", "Damian Lillard"],
    "SAC": ["Domantas Sabonis", "Dylan Cardwell", "Dennis Schroder", "Zach LaVine", "DeMar DeRozan"],
    "SAS": ["Stephon Castle", "Devin Vassell","Julian Champagnie", "Harrison Barnes", "Victor Wembanyama"],
    "TOR": ["Brandon Ingram", "Immanuel Quickley", "Collin Murray-Boyles", "RJ Barrett", "Scottie Barnes"],
    "UTA": ["Lauri Markkanen", "Walker Kessler", "Kyle Filipowski", "Svi Mykhailiuk", "Keyonte George"],
    "WAS": ["Bilal Coulibaly", "Alex Sarr", "CJ McCollum", "Khris Middleton", "Kyshawn George"],
}

mainStartingFive = {}

teamStarPlayer = {
    "OKC": "Shai Gilgeous-Alexander", 
    "DEN": 'Nikola Jokić', 
    "NYK": 'Jalen Brunson', 
    "CLE": "Donovan Mitchell",
    "ORL": "Paolo Banchero", 
    "MIN": "Anthony Edwards", 
    "GSW": "Stephen Curry", 
    "LAL": 'Luka Dončić', 
    "HOU": "Kevin Durant",
    "SAS": "Victor Wembanyama", 
    "LAC": "Kawhi Leonard", 
    "DET": "Cade Cunningham",
    "ATL": "Trae Young",
    "SAC": "Zach LaVine", 
    "DAL": "Anthony Davis",
    "MIA": "Tyler Herro",
    "TOR": "Scottie Barnes",
    "MEM": "Ja Morant",
    "PHI": "Tyrese Maxey",
    "BOS": "Jaylen Brown",
    "IND": "Pascal Siakam",
    "PHX": "Devin Booker",
    "MIL": "Giannis Antetokounmpo",
    "NOP": "Zion Williamson",
    "POR": "Deni Avdija",
    "CHI": "Coby White",
    "UTA": "Lauri Markkanen",
    "CHA": "LaMelo Ball",
    "BKN": "Cam Thomas",
    "WAS": "CJ McCollum"
}